(async()=>{
  const $=s=>document.querySelector(s),A=$('#app'),H=window.QHELP,SMART=window.QSMART,CH=window.QCHAPTER;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pct=(a,b)=>b?Math.round(100*a/b):0;
  let chunks=[];for(let i=1;i<=12;i++){const r=await fetch(`bank-${String(i).padStart(2,'0')}.txt`,{cache:'no-store'});if(!r.ok)throw Error('Fichier banque manquant');chunks.push((await r.text()).trim())}
  const bin=atob(chunks.join('')),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);
  const ds=new DecompressionStream('gzip'),p=JSON.parse(await new Response(new Blob([u]).stream().pipeThrough(ds)).text());
  const cats=p.c,pref=['HIS','GEO','EMC','ACT','ORG','MAT','LOG','CG'],n=Array(8).fill(0);
  const raw=p.k.map(([ci,page,text])=>({ci,page,text,cat:cats[ci],id:`${pref[ci]}-${String(++n[ci]).padStart(4,'0')}`}));
  const K=SMART.enrich(raw),EL=['Mathématiques','Raisonnement logique'];
  const EXMAP={
    'Mathématiques':{
      'A. Nombres et arithmétique':['PGCD','Binaire','Pourcentages','Nombres premiers'],
      'B. Algèbre':['Équation','Factorisation'],
      'C. Mesures et géométrie':['Échelle','Volume','Aire appliquée'],
      'D. Mouvement et problèmes appliqués':['Vitesse','Horaires'],
      'E. Statistiques et probabilités':['Probabilité']
    },
    'Raisonnement logique':{
      'A. Logique mathématique':['Âges'],
      'B. Logique verbale':['Correspondance lettres','Code verbal','Syllogisme'],
      'C. Logique spatiale':['Dominos','Matrice','Rotation'],
      'D. Logique organisationnelle':['Calendrier'],
      'E. Suites et structures':['Suite numérique','Nombre manquant'],
      'F. Logique combinatoire et tableaux de déduction':['Parenté','Contraintes','Déduction']
    }
  },EXCACHE={};
  let P=JSON.parse(localStorage.getItem('qcm-v10')||'{}'),E=JSON.parse(localStorage.getItem('qcm-ex-v3')||'{}'),route='home';
  let selectedCat=localStorage.getItem('qcm-last-cat')||cats[0],chapterChoice=null,topicChoice=null,mode='coverage',type=EL.includes(selectedCat)?'mixed':'knowledge',size=20,S=[],qi=0,sessionOk=0,sessionBad=0;
  const save=()=>localStorage.setItem('qcm-v10',JSON.stringify(P)),saveE=()=>localStorage.setItem('qcm-ex-v3',JSON.stringify(E));
  const rec=id=>P[id]||(P[id]={a:0,c:0,w:0,s:0});
  const st=id=>{const r=P[id];return!r||!r.a?'new':r.s>=2&&r.c>=2?'mastered':r.w&&r.s===0?'error':'seen'};
  const chaptersFor=c=>[...new Set(K.filter(x=>x.cat===c).map(x=>x.chapter))].filter(Boolean);
  const topicsFor=(c,ch)=>SMART.topics(c,K,ch).filter(Boolean);
  const resetScope=()=>{const chs=chaptersFor(selectedCat);chapterChoice=chs[0]||null;topicChoice=null;type=EL.includes(selectedCat)?'mixed':'knowledge';localStorage.setItem('qcm-last-cat',selectedCat)};
  if(!cats.includes(selectedCat))selectedCat=cats[0];
  if(!chapterChoice)chapterChoice=chaptersFor(selectedCat)[0]||null;
  function go(r){route=r;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.r===r));render()}
  function ks(c){const a=K.filter(x=>x.cat===c);let seen=0,m=0,e=0;a.forEach(x=>{const z=st(x.id);if(z!=='new')seen++;if(z==='mastered')m++;if(z==='error')e++});return{t:a.length,seen,m,e}}
  function home(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length;A.innerHTML=`<div class="card hero"><h1>Choisis d’abord ce que tu veux travailler</h1><p class="muted">L’entraînement suit désormais le cours : matière → chapitre → sous-thème → question ciblée. Une question ne mélange plus plusieurs thèmes différents.</p><span class="tag">QCM ciblés</span> <span class="tag practice">Pièges plausibles</span></div><div class="card"><div class="stat">${pct(seen,K.length)} %</div><span class="muted">${seen}/${K.length} faits rencontrés · ${m} maîtrisés</span><div class="bar"><i style="width:${pct(seen,K.length)}%"></i></div></div><h2>Matières</h2><div class="grid">${cats.map(c=>{const s=ks(c);return`<div class="card cat" data-cat="${esc(c)}"><b>${esc(c)}</b><span class="muted">${chaptersFor(c).length} chapitres · ${s.e} fait(s) à revoir</span><div class="bar"><i style="width:${pct(s.seen,s.t)}%"></i></div>${EL.includes(c)?'<span class="tag practice">+ exercices type concours</span>':''}</div>`}).join('')}</div>`;document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selectedCat=b.dataset.cat;resetScope();mode='coverage';go('quiz')})}
  function quiz(){const chs=chaptersFor(selectedCat),tops=chapterChoice?topicsFor(selectedCat,chapterChoice):[];if(!EL.includes(selectedCat)&&type!=='knowledge')type='knowledge';A.innerHTML=`<div class="card scope"><div class="step"><span>1</span><b>Matière</b></div><div class="chips">${cats.map(c=>`<button class="chip ${selectedCat===c?'on':''}" data-c="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="card scope"><div class="step"><span>2</span><b>Chapitre</b></div><div class="chips"><button class="chip ${chapterChoice===null?'on':''}" data-ch="">Tous les chapitres</button>${chs.map(ch=>`<button class="chip ${chapterChoice===ch?'on':''}" data-ch="${esc(ch)}">${esc(ch)}</button>`).join('')}</div></div>${chapterChoice?`<div class="card scope"><div class="step"><span>3</span><b>Sous-thème</b></div><div class="chips"><button class="chip ${topicChoice===null?'on':''}" data-top="">Tout le chapitre</button>${tops.map(t=>`<button class="chip ${topicChoice===t?'on':''}" data-top="${esc(t)}">${esc(t)}</button>`).join('')}</div></div>`:`<div class="card"><p class="muted">Tu as choisi le mélange de tous les chapitres. Pour un entraînement plus précis, sélectionne un chapitre.</p></div>`}<div class="card scope"><div class="step"><span>4</span><b>Mode d’entraînement</b></div><div class="chips">${[['coverage','Apprentissage progressif'],['errors','Mes erreurs'],['random','Aléatoire']].map(x=>`<button class="chip ${mode===x[0]?'on':''}" data-m="${x[0]}">${x[1]}</button>`).join('')}</div>${EL.includes(selectedCat)?`<div class="chips"><button class="chip ${type==='knowledge'?'on':''}" data-t="knowledge">Connaissances</button><button class="chip ${type==='exercise'?'on':''}" data-t="exercise">Exercices</button><button class="chip ${type==='mixed'?'on':''}" data-t="mixed">Mixte</button></div><p class="muted small">Les exercices suivent le chapitre sélectionné lorsqu’un chapitre précis est choisi.</p>`:''}</div><div class="card"><label><b>Nombre de questions</b></label><select id="sz" class="field"><option>10</option><option ${size===20?'selected':''}>20</option><option ${size===50?'selected':''}>50</option><option ${size===100?'selected':''}>100</option></select></div><button id="launch" class="btn wide">Lancer ce QCM</button>`;
    document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{selectedCat=b.dataset.c;resetScope();quiz()});
    document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>{chapterChoice=b.dataset.ch||null;topicChoice=null;quiz()});
    document.querySelectorAll('[data-top]').forEach(b=>b.onclick=()=>{topicChoice=b.dataset.top||null;quiz()});
    document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{mode=b.dataset.m;quiz()});
    document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{type=b.dataset.t;quiz()});
    $('#sz').onchange=e=>size=+e.target.value;$('#launch').onclick=start
  }
  function orderedFacts(){let a=K.filter(x=>x.cat===selectedCat);if(chapterChoice)a=a.filter(x=>x.chapter===chapterChoice);if(topicChoice)a=a.filter(x=>x.topicName===topicChoice);if(mode==='errors')a=a.filter(x=>P[x.id]?.w);if(mode==='coverage')a.sort((x,y)=>({new:0,error:1,seen:2,mastered:3}[st(x.id)]-{new:0,error:1,seen:2,mastered:3}[st(y.id)])||((P[x.id]?.a||0)-(P[y.id]?.a||0)));else a=H.sh(a);return a}
  function knowledgeQuestions(count){const out=[];for(const x of orderedFacts()){if(out.length>=count)break;let q;try{q=SMART.make(x,K,H)}catch(e){console.warn('QCM ignoré',x.id,e)}if(q)out.push(q)}return out}
  function exercisePool(){const arr=selectedCat==='Mathématiques'?window.QMATH:window.QLOGIC;if(!EXCACHE[selectedCat])EXCACHE[selectedCat]=arr.map(fn=>{let topic='';try{topic=fn().topic}catch{}return{fn,topic}});let pool=EXCACHE[selectedCat];const wanted=chapterChoice&&EXMAP[selectedCat]?.[chapterChoice];if(wanted)pool=pool.filter(z=>wanted.includes(z.topic));return pool.length?pool.map(z=>z.fn):arr}
  function ex(){return H.pick(exercisePool())()}
  function start(){let k=size,e=0;if(type==='exercise'){k=0;e=size}else if(type==='mixed'&&EL.includes(selectedCat)){e=Math.round(size*.6);k=size-e}const exs=[];for(let i=0;i<e;i++)exs.push(ex());const know=knowledgeQuestions(k);S=H.sh([...know,...exs]);qi=0;sessionOk=0;sessionBad=0;if(!S.length){A.innerHTML=`<div class="card"><h2>Aucune question suffisamment fiable ici</h2><p class="muted">Je préfère ne pas afficher une question mal construite. Choisis un autre sous-thème ou le chapitre entier.</p><button class="btn" id="backq">Modifier la sélection</button></div>`;$('#backq').onclick=quiz;return}show()}
  function show(){const q=S[qi],ch=q.kind==='k'?q.chapter:'Exercice type concours',tp=q.kind==='k'?q.topic:q.topic;A.innerHTML=`<div class="breadcrumb"><b>${esc(q.cat)}</b><span>›</span><span>${esc(ch)}</span>${tp&&tp!==ch?`<span>›</span><span>${esc(tp)}</span>`:''}</div><div class="qmeta"><span>Question ${qi+1}/${S.length}</span><span class="tag ${q.kind==='ex'?'practice':''}">${q.kind==='ex'?'Exercice':'Connaissance ciblée'}</span></div><div class="bar"><i style="width:${pct(qi,S.length)}%"></i></div><div class="card quiz-card"><h2 class="question-title">${esc(q.prompt)}</h2>${q.html||''}${q.o.map((x,i)=>`<button class="opt" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(x)}</span></button>`).join('')}<div id="fb"></div></div>`;document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>answer(q,+b.dataset.i))}
  function answer(q,i){const ok=i===q.ans;ok?sessionOk++:sessionBad++;if(q.kind==='k'){const r=rec(q.x.id);r.a++;ok?(r.c++,r.s++):(r.w++,r.s=0);save()}else{const r=E[q.cat]||(E[q.cat]={a:0,c:0});r.a++;if(ok)r.c++;saveE()}document.querySelectorAll('.opt').forEach((b,j)=>{b.disabled=true;if(j===q.ans)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});const correct=q.o[q.ans];$('#fb').innerHTML=`<div class="feedback ${ok?'ok':'ko'}"><b>${ok?'Bonne réponse':'À revoir'}</b>${ok?'':`<p class="correct-answer"><strong>Bonne réponse :</strong> ${esc(correct)}</p>`}<p>${esc(q.why)}</p><small>${q.kind==='ex'?'Exercice type concours généré à partir du cours':'Cours · page '+q.x.page+(q.topic?' · '+esc(q.topic):'')}</small><div class="actions"><button class="btn" id="next">${qi+1<S.length?'Question suivante':'Voir le bilan'}</button></div></div>`;$('#next').onclick=()=>{qi++;qi<S.length?show():end()};setTimeout(()=>$('#fb')?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)}
  function end(){A.innerHTML=`<div class="card hero"><h1>Session terminée</h1><div class="score">${pct(sessionOk,S.length)} %</div><p>${sessionOk} bonne(s) réponse(s) · ${sessionBad} erreur(s) sur ${S.length} questions.</p><div class="actions"><button class="btn" id="again">Recommencer ce thème</button><button class="btn alt" id="change">Changer de thème</button></div></div>`;$('#again').onclick=start;$('#change').onclick=quiz}
  function inventory(){A.innerHTML=`<h2>Inventaire des connaissances</h2><p class="muted">L’inventaire conserve les faits du cours. L’application n’en transforme en QCM que lorsqu’elle peut construire une question ciblée et des réponses plausibles.</p><div class="filters"><input id="q" class="field" placeholder="Rechercher"><select id="cf" class="field"><option value="">Toutes les matières</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="sf" class="field"><option value="">Tous statuts</option><option value="new">Jamais vue</option><option value="seen">Vue</option><option value="error">À revoir</option><option value="mastered">Maîtrisée</option></select></div><div id="list"></div>`;['q','cf','sf'].forEach(x=>$('#'+x).oninput=list);list()}
  function list(){const q=($('#q')?.value||'').toLowerCase(),c=$('#cf')?.value||'',s=$('#sf')?.value||'',a=K.filter(x=>(!c||x.cat===c)&&(!s||st(x.id)===s)&&(!q||x.text.toLowerCase().includes(q))).slice(0,250);$('#list').innerHTML=a.map(x=>`<div class="card row"><code>${x.id} · ${esc(x.cat)} · ${esc(x.chapter)} · ${esc(x.topicName)} · p.${x.page}</code><p>${esc(x.text)}</p></div>`).join('')||'<div class="card">Aucun résultat.</div>'}
  function stats(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length,ma=E['Mathématiques']||{a:0,c:0},lo=E['Raisonnement logique']||{a:0,c:0};A.innerHTML=`<h2>Progression</h2><div class="grid"><div class="card"><div class="stat">${pct(seen,K.length)}%</div>faits rencontrés</div><div class="card"><div class="stat">${m}</div>faits maîtrisés</div><div class="card"><div class="stat">${ma.a?pct(ma.c,ma.a):0}%</div>réussite exercices maths</div><div class="card"><div class="stat">${lo.a?pct(lo.c,lo.a):0}%</div>réussite exercices logique</div></div><button class="btn bad" id="reset">Réinitialiser la progression</button>`;$('#reset').onclick=()=>{if(confirm('Effacer toute la progression ?')){P={};E={};save();saveE();stats()}}}
  function render(){route==='home'?home():route==='quiz'?quiz():route==='inventory'?inventory():stats()}
  document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.r));render()
})().catch(e=>{document.querySelector('#app').innerHTML=`<div class="card"><h2>Impossible de charger l’application</h2><p>${String(e.message||e)}</p><p>Recharge la page une fois avec Internet.</p></div>`;console.error(e)});