(async()=>{
  const $=s=>document.querySelector(s),A=$('#app'),H=window.QHELP,QK=window.QKNOW,CH=window.QCHAPTER;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pct=(a,b)=>b?Math.round(100*a/b):0;
  let chunks=[];for(let i=1;i<=12;i++){const r=await fetch(`bank-${String(i).padStart(2,'0')}.txt`,{cache:'no-store'});if(!r.ok)throw Error('Fichier banque manquant');chunks.push((await r.text()).trim())}
  const bin=atob(chunks.join('')),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);
  const ds=new DecompressionStream('gzip'),p=JSON.parse(await new Response(new Blob([u]).stream().pipeThrough(ds)).text());
  const cats=p.c,pref=['HIS','GEO','EMC','ACT','ORG','MAT','LOG','CG'],n=Array(8).fill(0);
  const raw=p.k.map(([ci,page,text])=>({ci,page,text,cat:cats[ci],id:`${pref[ci]}-${String(++n[ci]).padStart(4,'0')}`}));
  const expanded=QK.expand(raw),K=expanded.filter(QK.quizworthy),EL=['Mathématiques','Raisonnement logique'];
  let P=JSON.parse(localStorage.getItem('qcm-v9')||'{}'),E=JSON.parse(localStorage.getItem('qcm-ex-v3')||'{}'),route='home',sel=new Set(cats),chapterSel=null,mode='coverage',type='mixed',size=20,S=[],qi=0;
  const save=()=>localStorage.setItem('qcm-v9',JSON.stringify(P)),saveE=()=>localStorage.setItem('qcm-ex-v3',JSON.stringify(E)),rec=id=>P[id]||(P[id]={a:0,c:0,w:0,s:0}),st=id=>{const r=P[id];return!r||!r.a?'new':r.s>=2&&r.c>=2?'mastered':r.w&&r.s===0?'error':'seen'};
  function ks(c){const a=K.filter(x=>x.cat===c);let seen=0,m=0,e=0;a.forEach(x=>{const z=st(x.id);if(z!=='new')seen++;if(z==='mastered')m++;if(z==='error')e++});return{t:a.length,seen,m,e}}
  function go(r){route=r;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.r===r));render()}
  function ex(cat){return H.pick(cat==='Mathématiques'?window.QMATH:window.QLOGIC)()}
  const currentCat=()=>sel.size===1?[...sel][0]:null;
  const chaptersFor=c=>[...new Set(K.filter(x=>x.cat===c).map(x=>CH.chapter(x)))];
  function resetChapters(){const c=currentCat();chapterSel=c?new Set(chaptersFor(c)):null}
  function home(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length;A.innerHTML=`<div class="card hero"><h1>Réviser par matière puis par chapitre</h1><p class="muted">Chaque matière suit maintenant la structure du cours. Tu peux travailler un chapitre précis avant de passer au mélange général. Les distracteurs sont d’abord choisis dans ce même chapitre.</p><span class="tag">Organisation par chapitres</span> <span class="tag practice">QCM plus cohérents</span><div class="actions"><button class="btn" id="cov">Continuer</button><button class="btn alt" id="err">Mes erreurs</button></div></div><div class="card"><div class="stat">${pct(seen,K.length)} %</div><span class="muted">${seen}/${K.length} faits vus · ${m} maîtrisés</span><div class="bar"><i style="width:${pct(seen,K.length)}%"></i></div></div><div class="grid">${cats.map(c=>{const s=ks(c);return`<div class="card cat" data-cat="${esc(c)}"><b>${esc(c)}</b><span class="muted">${s.t} faits · ${chaptersFor(c).length} chapitres · ${s.e} à revoir</span><div class="bar"><i style="width:${pct(s.seen,s.t)}%"></i></div>${EL.includes(c)?'<span class="tag practice">+ exercices</span>':''}</div>`}).join('')}</div>`;$('#cov').onclick=()=>{mode='coverage';type='mixed';sel=new Set(cats);chapterSel=null;go('quiz')};$('#err').onclick=()=>{mode='errors';type='knowledge';sel=new Set(cats);chapterSel=null;go('quiz')};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{sel=new Set([b.dataset.cat]);resetChapters();type=EL.includes(b.dataset.cat)?'mixed':'knowledge';go('quiz')})}
  function quiz(){const has=[...sel].some(c=>EL.includes(c)),c=currentCat(),chs=c?chaptersFor(c):[];if(!has&&type!=='knowledge')type='knowledge';A.innerHTML=`<h2>Nouvelle session</h2><div class="card"><b>Mode</b><div class="chips">${[['coverage','Couverture'],['errors','Erreurs'],['random','Aléatoire']].map(x=>`<button class="chip ${mode===x[0]?'on':''}" data-m="${x[0]}">${x[1]}</button>`).join('')}</div></div><div class="card"><b>Matières</b><div class="chips">${cats.map(cc=>`<button class="chip ${sel.has(cc)?'on':''}" data-c="${esc(cc)}">${esc(cc)}</button>`).join('')}</div></div>${c&&chs.length?`<div class="card"><b>Chapitres de ${esc(c)}</b><p class="muted small">Tu peux en choisir un seul ou en combiner plusieurs.</p><div class="chips"><button class="chip ${chapterSel&&chapterSel.size===chs.length?'on':''}" id="allchap">Tous</button>${chs.map(ch=>`<button class="chip ${chapterSel?.has(ch)?'on':''}" data-ch="${esc(ch)}">${esc(ch)}</button>`).join('')}</div></div>`:''}<div class="card"><b>Type de questions</b><div class="chips"><button class="chip ${type==='knowledge'?'on':''}" data-t="knowledge">QCM de connaissances</button><button class="chip ${type==='exercise'?'on':''}" data-t="exercise" ${has?'':'disabled'}>Exercices type concours</button><button class="chip ${type==='mixed'?'on':''}" data-t="mixed" ${has?'':'disabled'}>Mixte</button></div></div><div class="card"><select id="sz" class="field"><option>10</option><option ${size===20?'selected':''}>20</option><option ${size===50?'selected':''}>50</option><option ${size===100?'selected':''}>100</option></select></div><button id="launch" class="btn wide">Lancer</button>`;
    document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{mode=b.dataset.m;quiz()});document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{if(!b.disabled){type=b.dataset.t;quiz()}});document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const cc=b.dataset.c;if(sel.has(cc)&&sel.size>1)sel.delete(cc);else if(sel.size===1&&sel.has(cc)){}else sel=new Set([cc]);resetChapters();quiz()});
    document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>{const ch=b.dataset.ch;if(!chapterSel)chapterSel=new Set(chs);if(chapterSel.has(ch)&&chapterSel.size>1)chapterSel.delete(ch);else chapterSel.add(ch);quiz()});if($('#allchap'))$('#allchap').onclick=()=>{chapterSel=new Set(chs);quiz()};$('#sz').onchange=e=>size=+e.target.value;$('#launch').onclick=start}
  function orderedKnowledge(){let a=K.filter(x=>sel.has(x.cat));const c=currentCat();if(c&&chapterSel)a=a.filter(x=>chapterSel.has(CH.chapter(x)));if(mode==='errors')a=a.filter(x=>P[x.id]?.w);if(mode==='coverage')a.sort((x,y)=>({new:0,error:1,seen:2,mastered:3}[st(x.id)]-{new:0,error:1,seen:2,mastered:3}[st(y.id)])||((P[x.id]?.a||0)-(P[y.id]?.a||0)));else a=H.sh(a);return a}
  function know(count){const out=[];for(const x of orderedKnowledge()){if(out.length>=count)break;const q=QK.make(x,K,H);if(q)out.push(q)}return out}
  function start(){let e=0,k=size;if(type==='exercise'){e=size;k=0}else if(type==='mixed'&&[...sel].some(c=>EL.includes(c))){e=Math.round(size*([...sel].every(c=>EL.includes(c))?.65:.35));k=size-e}const exs=[],ec=[...sel].filter(c=>EL.includes(c));for(let i=0;i<e;i++)exs.push(ex(ec[i%ec.length]));S=H.sh([...know(k),...exs]);qi=0;if(!S.length){A.innerHTML='<div class="card"><h2>Aucune question disponible</h2><p class="muted">Essaie un autre chapitre ou une autre matière.</p></div>';return}show()}
  function show(){const q=S[qi],chap=q.kind==='k'?(q.chapter||CH.chapter(q.x)):'Exercice type concours';A.innerHTML=`<div class="qmeta"><span>${esc(q.cat)} · ${esc(chap)} · ${qi+1}/${S.length}</span><span class="tag ${q.kind==='ex'?'practice':''}">${esc(q.topic)}</span></div><div class="bar"><i style="width:${pct(qi,S.length)}%"></i></div><div class="card quiz-card"><h2 class="question-title">${esc(q.prompt)}</h2>${q.html||''}${q.o.map((x,i)=>`<button class="opt" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(x)}</span></button>`).join('')}<div id="fb"></div></div>`;document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>answer(q,+b.dataset.i))}
  function answer(q,i){const ok=i===q.ans;if(q.kind==='k'){const r=rec(q.x.id);r.a++;ok?(r.c++,r.s++):(r.w++,r.s=0);save()}else{const r=E[q.cat]||(E[q.cat]={a:0,c:0});r.a++;if(ok)r.c++;saveE()}document.querySelectorAll('.opt').forEach((b,j)=>{b.disabled=true;if(j===q.ans)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});$('#fb').innerHTML=`<div class="feedback ${ok?'ok':'ko'}"><b>${ok?'Bonne réponse':'À revoir'}</b><p>${esc(q.why)}</p><small>${q.kind==='ex'?'Exercice type concours généré à partir du cours':'Cours · page '+q.x.page+' · '+esc(CH.chapter(q.x))}</small><div class="actions"><button class="btn" id="next">${qi+1<S.length?'Question suivante':'Bilan'}</button></div></div>`;$('#next').onclick=()=>{qi++;qi<S.length?show():end()};setTimeout(()=>$('#fb')?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)}
  function end(){A.innerHTML=`<div class="card hero"><h1>Session terminée</h1><p>${S.length} questions travaillées, dont ${S.filter(x=>x.kind==='ex').length} exercices de résolution.</p><div class="actions"><button class="btn" id="again">Nouvelle session</button><button class="btn alt" id="back">Accueil</button></div></div>`;$('#again').onclick=quiz;$('#back').onclick=()=>go('home')}
  function inventory(){A.innerHTML=`<h2>Inventaire — ${K.length} faits révisables</h2><p class="muted">Chaque fait est maintenant rattaché à un chapitre du cours.</p><div class="filters"><input id="q" class="field" placeholder="Rechercher"><select id="cf" class="field"><option value="">Toutes</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="sf" class="field"><option value="">Tous statuts</option><option value="new">Jamais vue</option><option value="seen">Vue</option><option value="error">À revoir</option><option value="mastered">Maîtrisée</option></select></div><div id="list"></div>`;['q','cf','sf'].forEach(x=>$('#'+x).oninput=list);list()}
  function list(){const q=($('#q')?.value||'').toLowerCase(),c=$('#cf')?.value||'',s=$('#sf')?.value||'',a=K.filter(x=>(!c||x.cat===c)&&(!s||st(x.id)===s)&&(!q||x.text.toLowerCase().includes(q))).slice(0,300);$('#list').innerHTML=a.map(x=>`<div class="card row"><code>${x.id} · ${esc(x.cat)} · ${esc(CH.chapter(x))} · p.${x.page} · ${st(x.id)}</code><p>${esc(x.text)}</p></div>`).join('')||'<div class="card">Aucun résultat.</div>'}
  function stats(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length,ma=E['Mathématiques']||{a:0,c:0},lo=E['Raisonnement logique']||{a:0,c:0};A.innerHTML=`<h2>Progression</h2><div class="grid"><div class="card"><div class="stat">${pct(seen,K.length)}%</div>faits rencontrés</div><div class="card"><div class="stat">${m}</div>maîtrisés</div><div class="card"><div class="stat">${ma.a?pct(ma.c,ma.a):0}%</div>réussite maths (${ma.a} ex.)</div><div class="card"><div class="stat">${lo.a?pct(lo.c,lo.a):0}%</div>réussite logique (${lo.a} ex.)</div></div><button class="btn bad" id="reset">Réinitialiser</button>`;$('#reset').onclick=()=>{if(confirm('Tout effacer ?')){P={};E={};save();saveE();stats()}}}
  function render(){route==='home'?home():route==='quiz'?quiz():route==='inventory'?inventory():stats()}
  document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.r));render()
})().catch(e=>{document.querySelector('#app').innerHTML=`<div class="card"><h2>Impossible de charger l’application</h2><p>${String(e.message||e)}</p><p>Recharge la page avec Internet une fois.</p></div>`;console.error(e)});