(async()=>{
  const $=s=>document.querySelector(s),A=$('#app'),H=window.QHELP,SMART=window.QSMART,CH=window.QCHAPTER;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const pct=(a,b)=>b?Math.round(100*a/b):0;
  let chunks=[];for(let i=1;i<=12;i++){const r=await fetch(`bank-${String(i).padStart(2,'0')}.txt`,{cache:'no-store'});if(!r.ok)throw Error('Fichier banque manquant');chunks.push((await r.text()).trim())}
  const bin=atob(chunks.join('')),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);
  const ds=new DecompressionStream('gzip'),p=JSON.parse(await new Response(new Blob([u]).stream().pipeThrough(ds)).text());
  const cats=p.c,pref=['HIS','GEO','EMC','ACT','ORG','MAT','LOG','CG'],n=Array(8).fill(0);
  const raw=p.k.map(([ci,page,text])=>({ci,page,text,cat:cats[ci],id:`${pref[ci]}-${String(++n[ci]).padStart(4,'0')}`}));
  const K=SMART.enrich(raw),EL=['Mathématiques','Raisonnement logique'],MATH='Mathématiques';
  const LOGMAP={
    'A. Logique mathématique':['Âges'],
    'B. Logique verbale':['Correspondance lettres','Code verbal','Syllogisme'],
    'C. Logique spatiale':['Dominos','Matrice','Rotation'],
    'D. Logique organisationnelle':['Calendrier'],
    'E. Suites et structures':['Suite numérique','Nombre manquant'],
    'F. Logique combinatoire et tableaux de déduction':['Parenté','Contraintes','Déduction']
  };
  const COURSE={gcd:'pgcd',prime:'premiers',divisibility:'premiers','reduce-fraction':'pgcd','fraction-share':'pgcd','fraction-arithmetic':'pgcd',discount:'pourcentages','percent-increase':'pourcentages','percent-complement':'pourcentages','successive-rates':'pourcentages','nested-percent':'pourcentages','reverse-discount':'pourcentages','election-percent':'pourcentages','interest-rate':'pourcentages',yield:'pourcentages','vat-discount':'pourcentages','ht-ttc':'pourcentages','linear-equation':'equations',system:'equations','inequality-product':'equations','product-roots':'equations','solution-check':'equations',distribution:'equations','break-even':'equations','line-equation':'equations','mixed-consumption':'equations','symbol-puzzle':'equations','target-average':'equations','diff-squares':'factorisation','factor-quadratic':'factorisation','perfect-square-factor':'factorisation','factor-common':'factorisation','identity-difference':'factorisation','expand-square':'factorisation','scale-area':'echelle','scale-distance':'echelle','area-scale-factor':'echelle','material-volume':'volumes','cylinder-fill':'volumes','cuboid-volume':'volumes','sphere-area':'volumes','flow-remaining':'volumes','compare-speeds':'vitesse',pursuit:'vitesse','two-phase-speed':'vitesse','arrival-time':'horaires','add-durations':'horaires','work-schedule':'horaires','custom-time-system':'horaires','semester-minutes':'horaires','probability-list':'probabilites','prob-no-replace':'probabilites','compare-prob':'probabilites','dice-sum':'probabilites',median:'probabilites','median-mean':'probabilites','modal-class':'probabilites','weighted-mean':'probabilites','frequency-mean':'probabilites','area-compare':'aires','paint-room':'aires','triangle-area-units':'aires','circle-area':'aires','symmetry-triangle':'aires',homothety:'aires','pyth-circle':'aires',pythagoras:'aires','isosceles-right':'aires',orthocenter:'aires','triangle-angles':'aires','trig-tan':'aires','line-defs':'aires'};
  const EXCACHE={};
  let P=JSON.parse(localStorage.getItem('qcm-v10')||'{}'),E=JSON.parse(localStorage.getItem('qcm-ex-v4')||'{}'),route='home';
  let selectedCat=localStorage.getItem('qcm-last-cat')||cats[0],chapterChoice=null,topicChoice=null,mode='coverage',type=EL.includes(selectedCat)?'mixed':'knowledge',size=20,S=[],qi=0,sessionOk=0,sessionBad=0;
  const save=()=>localStorage.setItem('qcm-v10',JSON.stringify(P)),saveE=()=>localStorage.setItem('qcm-ex-v4',JSON.stringify(E));
  const rec=id=>P[id]||(P[id]={a:0,c:0,w:0,s:0});
  const st=id=>{const r=P[id];return!r||!r.a?'new':r.s>=2&&r.c>=2?'mastered':r.w&&r.s===0?'error':'seen'};
  const mathTemplates=()=>Object.values(window.QMATH_BANK?.templates||{});
  const chaptersFor=c=>c===MATH?[...new Set(mathTemplates().map(x=>x.chapter))]:[...new Set(K.filter(x=>x.cat===c).map(x=>x.chapter))].filter(Boolean);
  const topicsFor=(c,ch)=>c===MATH?[...new Set(mathTemplates().filter(x=>!ch||x.chapter===ch).map(x=>x.title))]:SMART.topics(c,K,ch).filter(Boolean);
  const resetScope=()=>{const chs=chaptersFor(selectedCat);chapterChoice=selectedCat===MATH?null:(chs[0]||null);topicChoice=null;type=selectedCat===MATH?'exercise':selectedCat==='Raisonnement logique'?'mixed':'knowledge';size=20;localStorage.setItem('qcm-last-cat',selectedCat)};
  if(!cats.includes(selectedCat))selectedCat=cats[0];
  if(selectedCat!==MATH&&!chapterChoice)chapterChoice=chaptersFor(selectedCat)[0]||null;
  if(selectedCat===MATH)type='exercise';
  function go(r){route=r;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.r===r));render()}
  function ks(c){const a=K.filter(x=>x.cat===c);let seen=0,m=0,e=0;a.forEach(x=>{const z=st(x.id);if(z!=='new')seen++;if(z==='mastered')m++;if(z==='error')e++});return{t:a.length,seen,m,e}}
  function home(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length;A.innerHTML=`<div class="card hero"><h1>Choisis ce que tu veux travailler</h1><p class="muted">Connaissances : matière → chapitre → sous-thème. En mathématiques : exercices uniquement, avec des énoncés complets et des variantes numériques renouvelables.</p><span class="tag">QCM pédagogiques</span> <span class="tag practice">Maths : 110 formats couverts</span></div><div class="card"><div class="stat">${pct(seen,K.length)} %</div><span class="muted">${seen}/${K.length} faits rencontrés · ${m} maîtrisés</span><div class="bar"><i style="width:${pct(seen,K.length)}%"></i></div></div><h2>Matières</h2><div class="grid">${cats.map(c=>{const s=ks(c);return`<div class="card cat" data-cat="${esc(c)}"><b>${esc(c)}</b><span class="muted">${chaptersFor(c).length} chapitres${c===MATH?' · 95 familles · parcours 110 formats':' · '+s.e+' fait(s) à revoir'}</span><div class="bar"><i style="width:${pct(s.seen,s.t)}%"></i></div>${EL.includes(c)?'<span class="tag practice">+ exercices type concours</span>':''}</div>`}).join('')}</div>`;document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{selectedCat=b.dataset.cat;resetScope();mode='coverage';go('quiz')})}
  function quiz(){const chs=chaptersFor(selectedCat),tops=chapterChoice?topicsFor(selectedCat,chapterChoice):[];if(selectedCat===MATH)type='exercise';else if(!EL.includes(selectedCat)&&type!=='knowledge')type='knowledge';const math=selectedCat===MATH;A.innerHTML=`<div class="card scope"><div class="step"><span>1</span><b>Matière</b></div><div class="chips">${cats.map(c=>`<button class="chip ${selectedCat===c?'on':''}" data-c="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="card scope"><div class="step"><span>2</span><b>Chapitre</b></div><div class="chips"><button class="chip ${chapterChoice===null?'on':''}" data-ch="">Tous les chapitres</button>${chs.map(ch=>`<button class="chip ${chapterChoice===ch?'on':''}" data-ch="${esc(ch)}">${esc(ch)}</button>`).join('')}</div></div>${chapterChoice?`<div class="card scope"><div class="step"><span>3</span><b>${math?'Type d’exercice':'Sous-thème'}</b></div><div class="chips"><button class="chip ${topicChoice===null?'on':''}" data-top="">${math?'Tous les types du chapitre':'Tout le chapitre'}</button>${tops.map(t=>`<button class="chip ${topicChoice===t?'on':''}" data-top="${esc(t)}">${esc(t)}</button>`).join('')}</div>${math?'<p class="muted small">Si tu choisis un type précis, les exercices gardent exactement la même structure et seuls les nombres changent.</p>':''}</div>`:''}${math?`<div class="card scope"><div class="step"><span>4</span><b>Entraînement mathématique</b></div><p>Les questions de connaissances automatiques sont désactivées en maths : tu travailles uniquement sur des exercices à résoudre.</p><p class="muted small">Le parcours complet couvre les 110 emplacements du QCM de référence avec des exercices originaux de même compétence. Les abréviations importantes sont développées dans les énoncés.</p></div>`:`<div class="card scope"><div class="step"><span>4</span><b>Mode d’entraînement</b></div><div class="chips">${[['coverage','Apprentissage progressif'],['errors','Mes erreurs'],['random','Aléatoire']].map(x=>`<button class="chip ${mode===x[0]?'on':''}" data-m="${x[0]}">${x[1]}</button>`).join('')}</div>${selectedCat==='Raisonnement logique'?`<div class="chips"><button class="chip ${type==='knowledge'?'on':''}" data-t="knowledge">Connaissances</button><button class="chip ${type==='exercise'?'on':''}" data-t="exercise">Exercices</button><button class="chip ${type==='mixed'?'on':''}" data-t="mixed">Mixte</button></div>`:''}</div>`}<div class="card"><label><b>Nombre de questions</b></label><select id="sz" class="field"><option value="10">10</option><option value="20" ${size===20?'selected':''}>20</option><option value="50" ${size===50?'selected':''}>50</option>${math?'<option value="110" '+(size===110?'selected':'')+'>110 — parcours complet</option>':'<option value="100" '+(size===100?'selected':'')+'>100</option>'}</select></div><button id="launch" class="btn wide">Lancer ce QCM</button>`;
    document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{selectedCat=b.dataset.c;resetScope();quiz()});
    document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>{chapterChoice=b.dataset.ch||null;topicChoice=null;quiz()});
    document.querySelectorAll('[data-top]').forEach(b=>b.onclick=()=>{topicChoice=b.dataset.top||null;quiz()});
    document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{mode=b.dataset.m;quiz()});
    document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{type=b.dataset.t;quiz()});
    $('#sz').onchange=e=>size=+e.target.value;$('#launch').onclick=start
  }
  function orderedFacts(){let a=K.filter(x=>x.cat===selectedCat);if(chapterChoice)a=a.filter(x=>x.chapter===chapterChoice);if(topicChoice)a=a.filter(x=>x.topicName===topicChoice);if(mode==='errors')a=a.filter(x=>P[x.id]?.w);if(mode==='coverage')a.sort((x,y)=>({new:0,error:1,seen:2,mastered:3}[st(x.id)]-{new:0,error:1,seen:2,mastered:3}[st(y.id)])||((P[x.id]?.a||0)-(P[y.id]?.a||0)));else a=H.sh(a);return a}
  function knowledgeQuestions(count){const out=[];for(const x of orderedFacts()){if(out.length>=count)break;let q;try{q=SMART.make(x,K,H)}catch(e){console.warn('QCM ignoré',x.id,e)}if(q)out.push(q)}return out}
  function logicPool(){if(!EXCACHE.logic)EXCACHE.logic=window.QLOGIC.map(fn=>{let z;try{z=fn()}catch{}return{fn,topic:z?.topic||''}});let pool=EXCACHE.logic;const wanted=chapterChoice&&LOGMAP[chapterChoice];if(wanted)pool=pool.filter(z=>wanted.includes(z.topic));return pool.length?pool.map(z=>z.fn):window.QLOGIC}
  function mathPool(){let arr=mathTemplates().filter(t=>(!chapterChoice||t.chapter===chapterChoice)&&(!topicChoice||t.title===topicChoice));return arr.map(t=>t.make)}
  function makeMathSession(count){if(!chapterChoice&&!topicChoice&&count===110)return H.sh(window.QMATH.map(fn=>fn()));const pool=mathPool();if(!pool.length)return[];const out=[];let cycle=[];for(let i=0;i<count;i++){if(!cycle.length)cycle=H.sh(pool);const fn=cycle.pop();out.push(fn())}return out}
  function makeLogicSession(count){const pool=logicPool(),out=[];for(let i=0;i<count;i++)out.push(H.pick(pool)());return out}
  function start(){if(selectedCat===MATH){S=makeMathSession(size)}else{let k=size,e=0;if(type==='exercise'){k=0;e=size}else if(type==='mixed'&&selectedCat==='Raisonnement logique'){e=Math.round(size*.6);k=size-e}const exs=selectedCat==='Raisonnement logique'?makeLogicSession(e):[];S=H.sh([...knowledgeQuestions(k),...exs])}qi=0;sessionOk=0;sessionBad=0;if(!S.length){A.innerHTML=`<div class="card"><h2>Aucune question disponible ici</h2><p class="muted">Choisis un autre chapitre ou un autre type d’exercice.</p><button class="btn" id="backq">Modifier la sélection</button></div>`;$('#backq').onclick=quiz;return}show()}
  function renew(q){if(q.kind!=='ex'||q.cat!==MATH||!q.renewable||!window.QMATH_BANK)return;const nq=window.QMATH_BANK.byId(q.templateId);if(!nq)return;nq.referenceType=q.referenceType;nq.referenceLabel=q.referenceLabel;S[qi]=nq;show()}
  function show(){const q=S[qi],ch=q.kind==='k'?q.chapter:(q.chapter||'Exercice type concours'),tp=q.kind==='k'?q.topic:(q.templateTitle||q.topic);const renewBtn=q.kind==='ex'&&q.cat===MATH&&q.renewable?`<button class="chip renew" id="renew">↻ Nouveaux nombres</button>`:'';A.innerHTML=`<div class="breadcrumb"><b>${esc(q.cat)}</b><span>›</span><span>${esc(ch)}</span>${tp&&tp!==ch?`<span>›</span><span>${esc(tp)}</span>`:''}</div><div class="qmeta" data-template="${esc(q.templateId||'')}"><span>Question ${qi+1}/${S.length}${q.referenceLabel?' · '+esc(q.referenceLabel):''}</span><span class="tag ${q.kind==='ex'?'practice':''}">${q.kind==='ex'?'Exercice':'Connaissance ciblée'}</span></div><div class="bar"><i style="width:${pct(qi,S.length)}%"></i></div>${renewBtn?`<div class="renew-row"><span class="muted small">Même type d’exercice, autre variante numérique</span>${renewBtn}</div>`:''}<div class="card quiz-card"><h2 class="question-title">${esc(q.prompt)}</h2>${q.html||''}${q.o.map((x,i)=>`<button class="opt" data-i="${i}"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(x)}</span></button>`).join('')}<div id="fb"></div></div>`;document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>answer(q,+b.dataset.i));if($('#renew'))$('#renew').onclick=()=>renew(q)}
  function answer(q,i){const ok=i===q.ans;ok?sessionOk++:sessionBad++;if(q.kind==='k'){const r=rec(q.x.id);r.a++;ok?(r.c++,r.s++):(r.w++,r.s=0);save()}else{const key=q.cat===MATH?`Math:${q.templateId||q.topic}`:q.cat;const r=E[key]||(E[key]={a:0,c:0});r.a++;if(ok)r.c++;saveE()}document.querySelectorAll('.opt').forEach((b,j)=>{b.disabled=true;if(j===q.ans)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});const correct=q.o[q.ans],anchor=q.cat===MATH?(COURSE[q.templateId]||''):'';const course=q.kind==='ex'&&q.cat===MATH&&!ok?`<a class="btn alt" href="cours-maths.html${anchor?'#'+anchor:''}" target="_blank" rel="noopener" style="text-decoration:none">📘 Voir le cours correspondant</a>`:'';$('#fb').innerHTML=`<div class="feedback ${ok?'ok':'ko'}"><b>${ok?'Bonne réponse':'À revoir'}</b>${ok?'':`<p class="correct-answer"><strong>Bonne réponse :</strong> ${esc(correct)}</p>`}<p>${esc(q.why)}</p><small>${q.kind==='ex'?(q.templateTitle?'Type : '+esc(q.templateTitle):'Exercice type concours'):'Cours · page '+q.x.page+(q.topic?' · '+esc(q.topic):'')}</small><div class="actions">${course}<button class="btn" id="next">${qi+1<S.length?'Question suivante':'Voir le bilan'}</button></div></div>`;$('#next').onclick=()=>{qi++;qi<S.length?show():end()};setTimeout(()=>$('#fb')?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)}
  function end(){A.innerHTML=`<div class="card hero"><h1>Session terminée</h1><div class="score">${pct(sessionOk,S.length)} %</div><p>${sessionOk} bonne(s) réponse(s) · ${sessionBad} erreur(s) sur ${S.length} questions.</p><div class="actions"><button class="btn" id="again">Recommencer ce thème</button><button class="btn alt" id="change">Changer de thème</button></div></div>`;$('#again').onclick=start;$('#change').onclick=quiz}
  function inventory(){A.innerHTML=`<h2>Inventaire des connaissances</h2><p class="muted">L’inventaire conserve les faits du cours. En mathématiques, l’entraînement utilise une banque d’exercices séparée.</p><div class="filters"><input id="q" class="field" placeholder="Rechercher"><select id="cf" class="field"><option value="">Toutes les matières</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select id="sf" class="field"><option value="">Tous statuts</option><option value="new">Jamais vue</option><option value="seen">Vue</option><option value="error">À revoir</option><option value="mastered">Maîtrisée</option></select></div><div id="list"></div>`;['q','cf','sf'].forEach(x=>$('#'+x).oninput=list);list()}
  function list(){const q=($('#q')?.value||'').toLowerCase(),c=$('#cf')?.value||'',s=$('#sf')?.value||'',a=K.filter(x=>(!c||x.cat===c)&&(!s||st(x.id)===s)&&(!q||x.text.toLowerCase().includes(q))).slice(0,250);$('#list').innerHTML=a.map(x=>`<div class="card row"><code>${x.id} · ${esc(x.cat)} · ${esc(x.chapter)} · ${esc(x.topicName)} · p.${x.page}</code><p>${esc(x.text)}</p></div>`).join('')||'<div class="card">Aucun résultat.</div>'}
  function stats(){const seen=K.filter(x=>st(x.id)!=='new').length,m=K.filter(x=>st(x.id)==='mastered').length;const math=Object.entries(E).filter(([k])=>k.startsWith('Math:')).reduce((a,[,v])=>({a:a.a+(v.a||0),c:a.c+(v.c||0)}),{a:0,c:0}),lo=E['Raisonnement logique']||{a:0,c:0};A.innerHTML=`<h2>Progression</h2><div class="grid"><div class="card"><div class="stat">${pct(seen,K.length)}%</div>faits rencontrés</div><div class="card"><div class="stat">${m}</div>faits maîtrisés</div><div class="card"><div class="stat">${math.a?pct(math.c,math.a):0}%</div>réussite exercices maths (${math.a})</div><div class="card"><div class="stat">${lo.a?pct(lo.c,lo.a):0}%</div>réussite exercices logique (${lo.a})</div></div><button class="btn bad" id="reset">Réinitialiser la progression</button>`;$('#reset').onclick=()=>{if(confirm('Effacer toute la progression ?')){P={};E={};save();saveE();stats()}}}
  function render(){route==='home'?home():route==='quiz'?quiz():route==='inventory'?inventory():stats()}
  document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.r));render()
})().catch(e=>{document.querySelector('#app').innerHTML=`<div class="card"><h2>Impossible de charger l’application</h2><p>${String(e.message||e)}</p><p>Recharge la page une fois avec Internet.</p></div>`;console.error(e)});
