window.QLOGIC=(H=>[
()=>H.q('Raisonnement logique','Suite numérique',(()=>{let a=H.r(2,8),add=H.r(2,6),mul=H.pick([2,3]),s=[a,a+add,(a+add)*mul,(a+add)*mul+add,((a+add)*mul+add)*mul],c=s[4]+add;return[`Complétez : ${s.join(' ; ')} ; ?`,c,[c+add,c*mul,c-add],`La règle alterne +${add}, puis ×${mul}.`]})()),
()=>H.q('Raisonnement logique','Nombre manquant',(()=>{let l=H.r(3,10),r=H.r(2,7),b=H.r(2,7),c=r*b-l;return[`Règle : droite × bas − gauche. Gauche=${l}, droite=${r}, bas=${b}. Résultat ?`,c,[r*b+l,l*r-b,c+2],`${r}×${b}−${l}=${c}.`]})()),
()=>H.q('Raisonnement logique','Correspondance lettres',[`Si Nizard va à Dublin et Shyrel à Londres, où va Ethel si la 1re lettre du prénom = dernière de la ville et la dernière lettre = 1re de la ville ?`,'Lisbonne',['Berlin','Dublin','Rome'],'Ethel commence par E et finit par L : la ville doit commencer par L et finir par E.']),
()=>H.q('Raisonnement logique','Âges',(()=>{let b=H.r(7,12),ages={Brice:b,Louis:b+2,Néo:b-6,Harry:b+3},y=Object.entries(ages).sort((a,b)=>a[1]-b[1])[0][0];return[`Brice a ${b} ans. Louis a 2 ans de plus. Néo a 6 ans de moins. Harry a 3 ans de plus. Qui est le plus jeune ?`,y,['Brice','Louis','Harry','Néo'].filter(x=>x!==y),`Néo a ${b-6} ans : c’est le plus jeune.`]})()),
()=>H.q('Raisonnement logique','Code verbal',(()=>{let w=H.pick(['NOTE','EXAMEN','EFFICIENT','DOUANE','CONTROLE']);return[`Si un mot vaut son nombre de lettres, « ${w} » vaut ?`,w.length,[w.length-1,w.length+1,w.length-2],`${w} contient ${w.length} lettres.`]})()),
()=>H.q('Raisonnement logique','Dominos',['Suite : 1|2 ; 2|3 ; 3|4 ; 4|5 ; ?','5|6',['4|6','5|5','6|1'],'Chaque moitié augmente de 1.']),
()=>H.q('Raisonnement logique','Parenté',[`Pour mon père, la mère de ma mère est…`,'sa belle-mère',['sa sœur','sa tante','sa cousine'],'La mère de ma mère est ma grand-mère maternelle, donc la belle-mère de mon père.']),
()=>H.q('Raisonnement logique','Contraintes',[`Code à 3 chiffres distincts entre 1 et 5. 1er > somme des 2 derniers. Dernier = double du milieu. Somme > 7. Quel code ?`,'5-1-2',['4-2-1','5-2-1','3-1-2'],'5>1+2, 2=2×1 et 5+1+2=8.']),
()=>H.q('Raisonnement logique','Matrice',(()=>{let a=H.r(1,5),b=H.r(1,5),c=a+b,ans=a+1+b+2,html=`<p>Complétez la matrice :</p><table class="matrix"><tr><td>${a}</td><td>${b}</td><td>${c}</td></tr><tr><td>${a+1}</td><td>${b+2}</td><td>?</td></tr></table>`;return['Quel nombre remplace ?',ans,[ans-1,ans+1,c+1],'Dans chaque ligne, la 3e case est la somme des deux premières.',html]})()),
()=>H.q('Raisonnement logique','Calendrier',(()=>{let days=['lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche'],s=H.pick(days),add=H.pick([8,10,15,17,22]),c=days[(days.indexOf(s)+add)%7];return[`Si aujourd’hui est ${s}, quel jour sera-t-on dans ${add} jours ?`,c,H.sh(days.filter(x=>x!==c)).slice(0,3),`${add} ≡ ${add%7} modulo 7.`]})()),
()=>H.q('Raisonnement logique','Syllogisme',[`Tous les inspecteurs sont agents publics. Certains agents publics sont juristes. Quelle conclusion est nécessaire ?`,'Tous les inspecteurs sont agents publics',['Tous les agents publics sont inspecteurs','Tous les juristes sont inspecteurs','Aucun inspecteur n’est agent public'],'Seule la première proposition découle nécessairement des prémisses.']),
()=>H.q('Raisonnement logique','Déduction',[`Qui est à la caisse ?`,'Chloé',['Alice','Benoît','Impossible à déterminer'],'Benoît=stock ; Alice=accueil ; il reste caisse pour Chloé.',`<p>Trois personnes ont chacune une tâche différente :</p><ul><li>Alice n’est pas à la caisse.</li><li>Benoît est au stock.</li><li>Chloé n’est pas à l’accueil.</li></ul>`]),
()=>H.q('Raisonnement logique','Rotation',(()=>{let ar=['↑','→','↓','←'],i=H.r(0,3),s=[ar[i],ar[(i+1)%4],ar[(i+2)%4]],c=ar[(i+3)%4];return[`Rotation de 90° horaire : ${s.join('  ')}  ?`,c,ar.filter(x=>x!==c),'Chaque flèche tourne de 90° dans le sens horaire.']})())
])(window.QHELP);