window.QMATH=(H=>[
()=>H.q('Mathématiques','PGCD',(()=>{let a=H.r(18,50),b=H.r(12,40);return[`Quel est le PGCD de ${a} et ${b} ?`,H.gcd(a,b),[H.gcd(a,b)+1,Math.max(1,H.gcd(a,b)-1),a*b/H.gcd(a,b)],`Le PGCD de ${a} et ${b} est ${H.gcd(a,b)}.`]})()),
()=>H.q('Mathématiques','Binaire',(()=>{let x=H.r(10,63),b=x.toString(2);return[`Quelle est l’écriture binaire de ${x} ?`,b,[(x+1).toString(2),(x-1).toString(2),b.split('').reverse().join('')],`${x} = ${b}₂.`]})()),
()=>H.q('Mathématiques','Pourcentages',(()=>{let base=H.r(80,400),p=H.pick([10,15,20,25,30]),v=base*(1-p/100);return[`Un article coûte ${base} €. Remise de ${p} %. Quel est son nouveau prix ?`,H.fmt(v)+' €',[H.fmt(base*p/100)+' €',H.fmt(base*(1+p/100))+' €',H.fmt(base-p)+' €'],`${base} × ${1-p/100} = ${H.fmt(v)} €.`]})()),
()=>H.q('Mathématiques','Équation',(()=>{let a=H.r(2,7),x=H.r(2,12),b=H.r(-8,8),c=a*x+b;return[`Résolvez : ${a}x ${b>=0?'+ '+b:'− '+Math.abs(b)} = ${c}.`,`x = ${x}`,[`x = ${x+1}`,`x = ${Math.max(0,x-1)}`,`x = ${H.fmt(c/a)}`],`${a}x=${c-b}, donc x=${x}.`]})()),
()=>H.q('Mathématiques','Factorisation',(()=>{let k=H.r(2,6),a=H.r(2,8),b=H.r(2,k*a-1),c=`(${k}x-${k*a+b})(${k}x-${k*a-b})`;return[`Factorisez : ${k*k}(x-${a})² − ${b*b}.`,c,[`(${k}x-${k*a})²-${b*b}`,`(${k}x-${b})(${k}x+${b})`,`(${k}x-${k*a+b})²`],`On utilise u²−v²=(u−v)(u+v).`]})()),
()=>H.q('Mathématiques','Échelle',(()=>{let sc=H.pick([500,1000,1500]),l=H.pick([2,3,4,5]),w=H.pick([.5,.8,1,1.2]),L=l*sc/100,W=w*sc/100,a=L*W;return[`Plan au 1/${sc} : rectangle ${String(l).replace('.',',')} cm × ${String(w).replace('.',',')} cm. Aire réelle ?`,H.fmt(a)+' m²',[H.fmt(a*10)+' m²',H.fmt(a/10)+' m²',H.fmt(l*w*sc)+' m²'],`Dimensions réelles : ${H.fmt(L)} m × ${H.fmt(W)} m.`]})()),
()=>H.q('Mathématiques','Volume',(()=>{let r=H.r(2,5),h=H.r(2,5),v=3.14*r*r*h*2/3;return[`Cuve cylindrique : rayon ${r} m, hauteur ${h} m, remplie aux 2/3. π=3,14. Volume contenu ?`,H.fmt(v)+' m³',[H.fmt(v*1.5)+' m³',H.fmt(v/2)+' m³',H.fmt(3.14*r*r*h)+' m³'],`V=πr²h×2/3=${H.fmt(v)} m³.`]})()),
()=>H.q('Mathématiques','Vitesse',(()=>{let v=H.pick([60,72,80,90]),h=H.r(2,4),m=H.pick([15,30,45]),d=v*(h+m/60);return[`À ${v} km/h pendant ${h} h ${m} min, quelle distance ?`,H.fmt(d)+' km',[H.fmt(v*h)+' km',H.fmt(d+v/2)+' km',H.fmt(d-v/4)+' km'],`d=v×t=${H.fmt(d)} km.`]})()),
()=>H.q('Mathématiques','Nombres premiers',(()=>{let ps=H.sh([2,3,5,7,11,13,17]).slice(0,3),bad=H.pick([4,6,8,9,10,12,15,21,25]);return[`Lequel n’est pas premier ?`,bad,ps,`${bad} possède un diviseur autre que 1 et lui-même.`]})()),
()=>H.q('Mathématiques','Probabilité',(()=>{let t=H.pick([8,10,12,20]),g=H.r(1,t-1),d=H.gcd(g,t),c=`${g/d}/${t/d}`;return[`${g} cas favorables sur ${t} cas équiprobables. Probabilité ?`,c,[`${Math.min(t,g+1)}/${t}`,`${t-g}/${t}`,`1/${t}`],`P=${g}/${t}=${c}.`]})()),
()=>H.q('Mathématiques','Aire appliquée',(()=>{let L=H.r(4,8),W=H.r(3,6),hh=H.pick([2,2.5,3]),cov=H.pick([10,12,15]),s=2*L*hh+2*W*hh+L*W,p=Math.ceil(s/cov);return[`Pièce ${L}×${W}×${String(hh).replace('.',',')} m. On peint 4 murs + plafond. 1 pot couvre ${cov} m². Nombre minimal de pots ?`,p,[Math.max(1,p-1),p+1,p+2],`Surface=${H.fmt(s)} m² ; ${H.fmt(s/cov)} pots, donc on arrondit à ${p}.`]})()),
()=>H.q('Mathématiques','Horaires',(()=>{let dep=H.r(7,10)*60+H.pick([5,15,25,35,45]),dur=H.r(2,4)*60+H.pick([15,25,35,45]),st=H.r(8,25),t=dep+dur+st,c=`${Math.floor(t/60)%24} h ${String(t%60).padStart(2,'0')}`;return[`Départ ${Math.floor(dep/60)} h ${String(dep%60).padStart(2,'0')}, trajet ${Math.floor(dur/60)} h ${dur%60} min, arrêts ${st} min. Heure d’arrivée ?`,c,[`${Math.floor((t+10)/60)%24} h ${String((t+10)%60).padStart(2,'0')}`,`${Math.floor((t+60)/60)%24} h ${String(t%60).padStart(2,'0')}`,`${Math.floor((dep+dur)/60)%24} h ${String((dep+dur)%60).padStart(2,'0')}`],`On additionne trajet et arrêts : ${c}.`]})())
])(window.QHELP);