(()=>{
const A=document.getElementById('infoApp'),H=window.QHELP||{sh:a=>[...a].sort(()=>Math.random()-.5)},B=window.QINFO_BANK;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pct=(a,b)=>b?Math.round(100*a/b):0;
const Q=B.questions.map((q,i)=>({...q,id:`INF-${String(i+1).padStart(3,'0')}`}));
let P=JSON.parse(localStorage.getItem('qcm-info-v1')||'{}'),route='home',chapter=null,topic=null,mode='coverage',size=20,S=[],qi=0,okN=0,badN=0;
const save=()=>localStorage.setItem('qcm-info-v1',JSON.stringify(P));
const rec=id=>P[id]||(P[id]={a:0,c:0,w:0,s:0});
const st=id=>{const r=P[id];return!r||!r.a?'new':r.s>=2&&r.c>=2?'mastered':r.w&&r.s===0?'error':'seen'};
const chapterBy=id=>B.chapters.find(c=>c.id===id);
const qs=(ch=chapter,tp=null)=>Q.filter(q=>(!ch||q.c===ch)&&(!tp||q.t===tp));
const statsFor=ch=>{const a=qs(ch);let seen=0,m=0,e=0;a.forEach(q=>{const z=st(q.id);if(z!=='new')seen++;if(z==='mastered')m++;if(z==='error')e++});return{t:a.length,seen,m,e}};
function go(r){route=r;document.querySelectorAll('.info-nav button[data-r]').forEach(b=>b.classList.toggle('on',b.dataset.r===r));render()}
function home(){const total=statsFor(null),groups=[...new Set(B.chapters.map(c=>c.group))];A.innerHTML=`<div class="card hero info-intro"><h1>Informatique / Culture numérique</h1><p class="muted">Le cours est organisé selon le programme : socle de compétences numériques, administration numérique, puis réglementation. Chaque question teste une connaissance précise avec des réponses de même nature.</p><span class="tag">${Q.length} QCM pédagogiques</span> <span class="tag practice">10 chapitres</span><div class="actions"><button class="btn" id="startAll">Réviser tout</button><button class="btn alt" id="errors">Mes erreurs</button></div></div><div class="card"><div class="stat">${pct(total.seen,total.t)} %</div><span class="muted">${total.seen}/${total.t} questions rencontrées · ${total.m} maîtrisées · ${total.e} à revoir</span><div class="bar"><i style="width:${pct(total.seen,total.t)}%"></i></div></div>${groups.map(g=>`<div class="info-group">${esc(g)}</div><div class="grid">${B.chapters.filter(c=>c.group===g).map(c=>{const s=statsFor(c.id),topics=[...new Set(qs(c.id).map(q=>q.t))];return`<div class="card cat info-ch" data-ch="${c.id}"><div class="info-card-head"><div><b>${esc(c.title)}</b><span class="muted">${s.t} questions · ${topics.length} sous-thèmes</span></div><div class="stat">${pct(s.seen,s.t)}%</div></div><div class="bar"><i style="width:${pct(s.seen,s.t)}%"></i></div><div class="info-topic-list">${topics.slice(0,5).map(t=>`<span class="info-topic">${esc(t)}</span>`).join('')}</div><div class="info-scoreline"><span>${s.m} maîtrisées</span><span>${s.e} à revoir</span></div></div>`}).join('')}</div>`).join('')}`;
 document.getElementById('startAll').onclick=()=>{chapter=null;topic=null;mode='coverage';quizSetup()};document.getElementById('errors').onclick=()=>{chapter=null;topic=null;mode='errors';quizSetup()};document.querySelectorAll('.info-ch').forEach(x=>x.onclick=()=>{chapter=x.dataset.ch;topic=null;mode='coverage';quizSetup()});
}
function quizSetup(){route='quiz';document.querySelectorAll('.info-nav button[data-r]').forEach(b=>b.classList.remove('on'));const topics=chapter?[...new Set(qs(chapter).map(q=>q.t))]:[];A.innerHTML=`<div class="card scope"><div class="step"><span>1</span><b>Chapitre</b></div><div class="chips"><button class="chip ${chapter===null?'on':''}" data-ch="">Tous les chapitres</button>${B.chapters.map(c=>`<button class="chip ${chapter===c.id?'on':''}" data-ch="${c.id}">${esc(c.title)}</button>`).join('')}</div></div>${chapter?`<div class="card scope"><div class="step"><span>2</span><b>Sous-thème</b></div><div class="chips"><button class="chip ${topic===null?'on':''}" data-t="">Tout le chapitre</button>${topics.map(t=>`<button class="chip ${topic===t?'on':''}" data-t="${esc(t)}">${esc(t)}</button>`).join('')}</div></div>`:''}<div class="card scope"><div class="step"><span>3</span><b>Mode d’entraînement</b></div><div class="chips"><button class="chip ${mode==='coverage'?'on':''}" data-m="coverage">Apprentissage progressif</button><button class="chip ${mode==='errors'?'on':''}" data-m="errors">Mes erreurs</button><button class="chip ${mode==='random'?'on':''}" data-m="random">Aléatoire</button></div></div><div class="card"><label><b>Nombre de questions</b></label><select id="sz" class="field"><option value="10">10</option><option value="20" ${size===20?'selected':''}>20</option><option value="50" ${size===50?'selected':''}>50</option><option value="100" ${size===100?'selected':''}>100</option></select></div><button class="btn wide" id="launch">Lancer ce QCM</button>`;
 document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>{chapter=b.dataset.ch||null;topic=null;quizSetup()});document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{topic=b.dataset.t||null;quizSetup()});document.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{mode=b.dataset.m;quizSetup()});document.getElementById('sz').onchange=e=>size=+e.target.value;document.getElementById('launch').onclick=start;
}
function pool(){let a=qs(chapter,topic);if(mode==='errors')a=a.filter(q=>P[q.id]?.w);if(mode==='coverage')a.sort((x,y)=>({new:0,error:1,seen:2,mastered:3}[st(x.id)]-{new:0,error:1,seen:2,mastered:3}[st(y.id)])||((P[x.id]?.a||0)-(P[y.id]?.a||0)));else a=H.sh(a);return a}
function start(){S=pool().slice(0,size);qi=0;okN=0;badN=0;if(!S.length){A.innerHTML=`<div class="card"><h2>Aucune question disponible avec ce filtre</h2><p class="muted">Si tu as choisi « Mes erreurs », il est possible que tu n’aies encore aucune erreur enregistrée ici.</p><button class="btn" id="back">Modifier la sélection</button></div>`;document.getElementById('back').onclick=quizSetup;return}show()}
function show(){const q=S[qi],ch=chapterBy(q.c);A.innerHTML=`<div class="breadcrumb"><b>Informatique</b><span>›</span><span>${esc(ch?.title||'')}</span><span>›</span><span>${esc(q.t)}</span></div><div class="qmeta"><span>Question ${qi+1}/${S.length}</span><span class="tag practice">Connaissance ciblée</span></div><div class="bar"><i style="width:${pct(qi,S.length)}%"></i></div><div class="card"><h2 class="question-title">${esc(q.q)}</h2>${q.o.map((o,i)=>`<button class="opt info-opt" data-i="${i}"><span class="info-answer-letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}<div id="fb"></div></div>`;document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>answer(q,+b.dataset.i))}
function answer(q,i){const good=i===q.a,r=rec(q.id);r.a++;if(good){r.c++;r.s++;okN++}else{r.w++;r.s=0;badN++}save();document.querySelectorAll('.opt').forEach((b,j)=>{b.disabled=true;if(j===q.a)b.classList.add('correct');else if(j===i)b.classList.add('wrong')});document.getElementById('fb').innerHTML=`<div class="feedback ${good?'ok':'ko'}"><b>${good?'Bonne réponse':'À revoir'}</b><p>${esc(q.e)}</p><div class="info-source">${esc(q.s)}</div><div class="actions"><button class="btn" id="next">${qi+1<S.length?'Question suivante':'Voir le bilan'}</button><button class="btn alt" id="courseNow">📖 Voir le cours</button></div></div>`;document.getElementById('next').onclick=()=>{qi++;qi<S.length?show():end()};document.getElementById('courseNow').onclick=()=>{chapter=q.c;route='course';course()}}
function end(){A.innerHTML=`<div class="card hero"><h1>Session terminée</h1><div class="grid"><div class="card"><div class="stat">${okN}</div><span class="muted">bonnes réponses</span></div><div class="card"><div class="stat">${badN}</div><span class="muted">à revoir</span></div><div class="card"><div class="stat">${pct(okN,S.length)}%</div><span class="muted">réussite</span></div></div><div class="actions"><button class="btn" id="again">Nouvelle session</button><button class="btn alt" id="home">Accueil informatique</button></div></div>`;document.getElementById('again').onclick=quizSetup;document.getElementById('home').onclick=()=>go('home')}
function course(){route='course';document.querySelectorAll('.info-nav button[data-r]').forEach(b=>b.classList.toggle('on',b.dataset.r==='course'));const groups=[...new Set(B.chapters.map(c=>c.group))],chapters=chapter?B.chapters.filter(c=>c.id===chapter):B.chapters;A.innerHTML=`<div class="card hero"><h1>Cours de culture numérique</h1><p class="muted">Vue structurée des notions couvertes par les trois fascicules. Les points ci-dessous reprennent les connaissances utilisées dans les QCM et leurs pages sources.</p>${chapter?`<button class="btn alt" id="allCourse">Voir tout le cours</button>`:''}</div>${groups.map(g=>{const cc=chapters.filter(c=>c.group===g);if(!cc.length)return'';return`<div class="info-group">${esc(g)}</div>${cc.map(c=>{const list=qs(c.id),topics=[...new Set(list.map(q=>q.t))],s=statsFor(c.id);return`<div class="card"><div class="info-card-head"><div><h2>${esc(c.title)}</h2><span class="muted">${s.seen}/${s.t} questions vues · ${s.m} maîtrisées</span></div><button class="chip" data-revise="${c.id}">Réviser</button></div>${topics.map(t=>`<h3>${esc(t)}</h3>${list.filter(q=>q.t===t).map(q=>`<div class="info-course-point"><b>${esc(q.q)}</b><p>${esc(q.e)}</p><small>${esc(q.s)}</small></div>`).join('')}`).join('')}</div>`}).join('')}`}).join('')}`;if(document.getElementById('allCourse'))document.getElementById('allCourse').onclick=()=>{chapter=null;course()};document.querySelectorAll('[data-revise]').forEach(b=>b.onclick=()=>{chapter=b.dataset.revise;topic=null;mode='coverage';quizSetup()})}
function stats(){route='stats';document.querySelectorAll('.info-nav button[data-r]').forEach(b=>b.classList.toggle('on',b.dataset.r==='stats'));const total=statsFor(null);A.innerHTML=`<div class="card hero"><h1>Progression Informatique</h1><div class="stat">${pct(total.seen,total.t)}%</div><span class="muted">${total.seen}/${total.t} questions rencontrées · ${total.m} maîtrisées · ${total.e} à revoir</span><div class="bar"><i style="width:${pct(total.seen,total.t)}%"></i></div></div><div class="grid">${B.chapters.map(c=>{const s=statsFor(c.id);return`<div class="card"><b>${esc(c.title)}</b><div class="stat">${pct(s.seen,s.t)}%</div><div class="bar"><i style="width:${pct(s.seen,s.t)}%"></i></div><div class="info-scoreline"><span>${s.m} maîtrisées</span><span>${s.e} à revoir</span></div></div>`}).join('')}</div><button class="btn bad" id="resetInfo">Réinitialiser la progression Informatique</button>`;document.getElementById('resetInfo').onclick=()=>{if(confirm('Effacer uniquement la progression Informatique ?')){P={};save();stats()}}}
function render(){if(route==='home')home();else if(route==='course')course();else if(route==='stats')stats();else quizSetup()}
document.querySelectorAll('.info-nav button[data-r]').forEach(b=>b.onclick=()=>go(b.dataset.r));render();
})();