(()=>{
  const S=window.QSMART;if(!S)return;
  const old=S.make,clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const uniq=a=>[...new Set((a||[]).filter(Boolean).map(clean))];
  const source=x=>clean((x&&x.sourceText)|| (x&&x.text)||'');
  const low=x=>source(x).toLowerCase();
  const mk=(x,H,prompt,correct,wrong,why)=>{let d=uniq(wrong).filter(v=>v!==clean(correct));if(d.length<3)return null;d=H.sh(d).slice(0,3);const o=H.sh([clean(correct),...d]);return{kind:'k',cat:x.cat,chapter:x.chapter,topic:x.topicName,prompt:clean(prompt),o,ans:o.indexOf(clean(correct)),x,why:why||source(x)}};
  function curated(x,H){const t=low(x),s=source(x);
    // Reformulations pédagogiques des points faibles observés dans les captures.
    if(x.cat==='Histoire'&&/premières civilisations.*fleuves/.test(t))return mk(x,H,'Dans quel type de milieu se développent principalement les premières grandes civilisations comme l’Égypte et la Mésopotamie ?','Dans les vallées de grands fleuves',['Sur de hauts plateaux isolés','Dans de vastes déserts sans cours d’eau','Sur les littoraux océaniques uniquement'],s);
    if(x.cat==='Histoire'&&/athènes.*cité-état de l.attique/.test(t))return mk(x,H,'Quelle cité grecque est située en Attique ?','Athènes',['Sparte','Corinthe','Thèbes'],s);
    if(x.cat==='Histoire'&&/assemblée des citoyens.*tirage au sort.*ostracisme/.test(t))return mk(x,H,'Quel système politique repose notamment sur l’assemblée des citoyens, le tirage au sort et l’ostracisme ?','La démocratie athénienne',['L’oligarchie spartiate','La monarchie macédonienne','La République romaine'],s);
    if(x.cat==='Histoire'&&/agriculture.*riz en asie/.test(t))return mk(x,H,'À quelle région le cours associe-t-il la culture du riz dans les premières agricultures ?','À l’Asie',['Au Proche-Orient','À l’Amérique','À l’Europe du Nord'],s);
    if(x.cat==='Histoire'&&/domestication des plantes et des animaux.*villages.*poterie.*tissage/.test(t))return mk(x,H,'À quelle période de la Préhistoire associe-t-on la domestication des plantes et des animaux, l’apparition des villages, la poterie et le tissage ?','Au Néolithique',['Au Paléolithique','À l’âge du bronze','À l’Antiquité'],s);
    if(x.cat==='Histoire'&&/paléolithique.*nomades.*chasseurs.*cueilleurs/.test(t))return mk(x,H,'Quel mode de vie caractérise principalement les populations du Paléolithique ?','Le nomadisme fondé sur la chasse et la cueillette',['La sédentarité fondée sur l’agriculture et l’élevage','La vie urbaine organisée autour de cités-États','La vie dans des villages agricoles permanents'],s);
    if(x.cat==='Histoire'&&/néolithique.*sédentarisation/.test(t))return mk(x,H,'Quelle évolution caractérise le mieux le Néolithique par rapport au Paléolithique ?','Le développement de l’agriculture et de la sédentarisation',['L’apparition des premiers outils de pierre taillée','Le retour à un mode de vie exclusivement nomade','L’invention immédiate de l’écriture'],s);
    if(x.cat==='Histoire'&&/sumériens.*cunéiforme/.test(t))return mk(x,H,'Quel peuple est associé à l’invention de l’écriture cunéiforme ?','Les Sumériens',['Les Égyptiens','Les Phéniciens','Les Romains'],s);
    if(x.cat==='Histoire'&&/écriture hiéroglyphique/.test(t))return mk(x,H,'Quelle écriture est associée à l’Égypte antique ?','L’écriture hiéroglyphique',['L’écriture cunéiforme','L’alphabet phénicien','L’alphabet latin'],s);
    if(x.cat==='Histoire'&&/pharaon chef politique et religieux/.test(t))return mk(x,H,'Que signifie le caractère théocratique du pouvoir du pharaon ?','Le pharaon est à la fois chef politique et religieux',['Le pharaon exerce uniquement le pouvoir militaire','Le pharaon exerce uniquement une fonction religieuse','Les pouvoirs politique et religieux sont totalement séparés'],s);
    return null;
  }
  function optType(v){const s=clean(v);if(/^[-−]?\d{1,4}(?:\s*[–—-]\s*[-−]?\d{1,4})?$/.test(s))return'date';if(/^\d+(?:[,.]\d+)?\s*%$/.test(s))return'number';if(/^(?:Le|La|Les|L’|L')\s+(?:Conseil|Cour|Assemblée|Sénat|Parlement|Gouvernement|DG|Insee|AFT|Tracfin)/i.test(s)||/^(?:DGFiP|DGDDI|DGCCRF|Insee|Tracfin|AFT|ONU|OTAN|FMI|OMC|BCE)$/i.test(s))return'institution';if(/^(?:Au|À la|À l’|À l'|En|Dans|Sur)\s+/i.test(s))return'placephrase';if(/^[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜ][A-Za-zÀ-ÿ'’.-]+(?:\s+[A-ZÀÂÄÇÉÈÊËÎÏÔÖÙÛÜ][A-Za-zÀ-ÿ'’.-]+){0,3}$/.test(s))return'name';const w=s.split(/\s+/).length;if(w<=5)return'concept';return'sentence';}
  function fragment(v){const s=clean(v);return /^(?:J\.-C\.|av\. J\.-C\.|apr\. J\.-C\.|par\b|de\b|et\b|,|;|:)/i.test(s)||/\b(?:piège qcm|cours source|page \d+)\b/i.test(s)||s.length<2;}
  function acceptable(q){if(!q||q.kind!=='k'||!Array.isArray(q.o)||q.o.length!==4)return false;const p=clean(q.prompt);if(!p||/dans le cours|mentionné(?:e|es|s)? dans le cours|quelle notion correspond à cette définition|quelle information complète|que faut-il associer/i.test(p))return false;if(q.o.some(fragment))return false;const types=q.o.map(optType),u=uniq(types);if(u.length>2)return false;if(u.length===2){const counts=types.reduce((m,t)=>(m[t]=(m[t]||0)+1,m),{});if(Math.max(...Object.values(counts))<3)return false;}const lens=q.o.map(v=>clean(v).split(/\s+/).length).sort((a,b)=>a-b);if(lens[3]>Math.max(8,lens[1]*3))return false;return true;}
  S.make=function(x,K,H){const c=curated(x,H);if(c)return c;let q;try{q=old.call(S,x,K,H)}catch(e){console.warn('QCM rejeté',x&&x.id,e);return null}if(!q)return null;q.prompt=clean(q.prompt).replace(/\s+(?:dans|selon) le cours\s*\??$/i,' ?').replace(/mentionnées dans le cours/gi,'présentées ici');return acceptable(q)?q:null;};
})();