(()=>{
const APP=document.getElementById('programmeApp');
const STORE='programme-sept-2026-v1';
let state=JSON.parse(localStorage.getItem(STORE)||'{}');
let view=localStorage.getItem('programme-view')||'today';
const weeks=[
{id:'s1',title:'Semaine 1 — 1er au 4 septembre',goal:'Installer les méthodes et poser les premiers repères sans chercher encore la vitesse.',days:[
{date:'2026-09-01',label:'Mardi 1er septembre',priority:'Créer les trois outils de suivi : banque d’erreurs QCM, checklist NDS, suivi définitions/formules compta.',blocks:[['06:00–11:00','NDS',['Cours commande / sommaire / survol (30 min)','Vidéo 1/10 : 1 h 30 avec pauses de reformulation','Exercice 6 pages : de quoi parle la page ? + acteur / enjeu / levier','Réduire chaque page à 3 lignes puis classer les erreurs']],['12:00–13:30','QCM Agent',['Diagnostic des matières','Calcul mental, fractions, pourcentages','35–45 QCM maths/logique + banque d’erreurs']],['14:00–17:00','Comptabilité',['Fondamentaux : objet, principes, sources, IFRS','Vidéo comptabilité générale — passage 1, partie 1/2','8 questions de restitution sans notes','D001–D007 + F01']]]},
{date:'2026-09-02',label:'Mercredi 2 septembre',priority:'À la fin de la journée, connaître précisément le niveau de départ dans les trois matières.',blocks:[['06:00–11:00','NDS',['Corpus 10 pages : lecture chronométrée','Relevé d’idées + regroupement thématique','Construire 2 plans et choisir le meilleur','Introduction + réécriture courte ; 15 phrases lourdes à simplifier','Identifier les 3 obstacles qui coûtent le plus de temps']],['12:00–13:00','QCM Agent',['Proportions, règle de trois, moyennes, unités','QCM maths sans calculatrice + reprise des erreurs de mardi']],['14:00–17:00','Comptabilité',['Organisation comptable, plan comptable, partie double, livres, centralisateur','Vidéo comptabilité générale — passage 1, partie 2/2','15 exercices débit/crédit + classement des comptes','D008–D014 + F02']]]},
{date:'2026-09-03',label:'Jeudi 3 septembre',priority:'Pas de NDS : laisser reposer la méthode et consolider QCM + compta.',blocks:[['09:00–11:00','QCM Agent',['Logique : suites, analogies, déductions','QCM logique puis histoire-géographie grands repères']],['14:00–16:30','Comptabilité',['Vidéo comptabilité de gestion — passage 1 complet','Mini-test fondamentaux 15 min','D015–D021 + F03 ; rappels J+1/J+3/J+7']]]},
{date:'2026-09-04',label:'Vendredi 4 septembre',priority:'Finir tôt. Le week-end n’est pas une journée de rattrapage.',blocks:[['09:00–11:30','QCM Agent',['Rappel actif de la semaine','Mini-simulation mixte','Correction détaillée + banque d’erreurs : établir le score de référence']],['14:00–15:00','Comptabilité',['Rappel fondamental','10 mini-QCM + 5 écritures simples','D022–D028 + F04 ; mise à jour banque d’erreurs']]]}
]},
{id:'s2',title:'Semaine 2 — 7 au 11 septembre',goal:'Rendre le devoir NDS n°1 et consolider achats/ventes tout en sécurisant histoire-géo/EMC.',days:[
{date:'2026-09-07',label:'Lundi 7 septembre',priority:'NDS : apprendre à supprimer sans perdre l’essentiel.',blocks:[['06:00–11:00','NDS',['Cours : essentiel / exemple / détail','Vidéo 2/10 : lecture et exploitation du dossier','Dossier 12–15 pages : tableau document / idée / preuve utile','Supprimer 30 % des notes et réécrire celles trop proches du texte']],['12:00–13:30','QCM Agent',['Chronologie France/Europe, institutions civiques, valeurs républicaines','QCM histoire + EMC']],['14:00–17:00','Comptabilité',['Achats/ventes : réductions commerciales et financières','Analyse financière — passage 1, partie 1/2','8 écritures de factures simples','D029–D035 + F05']]]},
{date:'2026-09-08',label:'Mardi 8 septembre',priority:'Préparer le devoir du lendemain : aucun nouveau procédé NDS le soir.',blocks:[['06:00–11:00','NDS',['Lecture dossier partiel : 50 min max','Plan détaillé : 45 min','Rédiger 2 sous-parties ; avis/proposition complet 1 h 15','Relecture à froid + correction ciblée']],['12:00–13:30','QCM Agent',['Géographie France/UE/monde : territoires et grands ensembles','QCM géographie + erreurs J+1']],['14:00–17:00','Comptabilité',['Frais accessoires, avances/acomptes, créances/dettes d’exploitation','Analyse financière — passage 1, partie 2/2','12 écritures factures/avoirs/acomptes','D036–D042 + F06']]]},
{date:'2026-09-09',label:'Mercredi 9 septembre',priority:'Le devoir est le bloc prioritaire. Le QCM est volontairement raccourci à 1 h.',blocks:[['06:00–11:00','NDS',['06:00–10:00 : DEVOIR 1 en conditions concours','10:00–10:20 : noter les temps réels','10:20–10:45 : auto-évaluation omissions / plan / style / seconde partie','10:45–11:00 : déposer la copie + 1 priorité pour D2']],['12:00–13:00','QCM Agent',['Rappel maths/logique des erreurs S1','QCM mixte maths/logique/histoire-géo']],['14:00–17:00','Comptabilité',['Factures complexes : réductions, frais, TVA, règlement','Comptabilité générale — passage 2 complet','10 écritures mélangées sans cours','D043–D049 + F07']]]},
{date:'2026-09-10',label:'Jeudi 10 septembre',priority:'Ne pas ajouter de NDS : attendre la correction de la prépa et récupérer.',blocks:[['09:00–11:00','QCM Agent',['Consolidation histoire-géo/EMC + rappels espacés','Mini-test 25–30 questions chronométré']],['14:00–16:30','Comptabilité',['Consolidation achats/ventes/créances/dettes','Comptabilité de gestion — passage 2 complet','Cas de facturation complet + correction raisonnée','D050–D056 + F08']]]},
{date:'2026-09-11',label:'Vendredi 11 septembre',priority:'Jalon : D1 rendu + simulation Agent n°1 + 63 définitions / 9 formules vues.',blocks:[['09:00–11:30','QCM Agent',['Stratégie d’épreuve 10 min','Simulation Agent complète 1 h 30','Correction ciblée et classement des erreurs']],['14:00–15:00','Comptabilité',['20 min définitions/formules','25 min écritures flash ; 15 min banque d’erreurs','D057–D063 + F09']]]}
]},
{id:'s3',title:'Semaine 3 — 14 au 18 septembre',goal:'Accélérer la NDS, travailler TVA et sécuriser numérique/MEF/actualité.',days:[
{date:'2026-09-14',label:'Lundi 14 septembre',priority:'Objectif NDS : ne plus revenir constamment au dossier pendant la rédaction.',blocks:[['06:00–11:00','NDS',['Cours : tableaux de notes + reformulation','Vidéo 3/10 : prise de notes + correction vidéo n°1','20 pages : survol + lecture ciblée en 50 min','Transformer notes en plan ; vérifier la couverture des documents','Réécrire un passage après correction']],['12:00–13:30','QCM Agent',['Bases numériques : données, internet, sécurité','QCM environnement numérique']],['14:00–17:00','Comptabilité',['Personnel et organismes sociaux + introduction TVA','Analyse financière — passage 2, partie 1/2','6 écritures de paie/social + schéma TVA','D064–D070 + F10']]]},
{date:'2026-09-15',label:'Mardi 15 septembre',priority:'Ne pas dépasser les temps NDS : la vitesse devient un objectif de fond.',blocks:[['06:00–11:00','NDS',['20 pages : une page = une idée principale','Repérer acteurs / enjeux / leviers / chiffres / conséquences','Plan 45 min ; introduction / transitions','Avis/proposition 1 h 15 + correction avec grille']],['12:00–13:30','QCM Agent',['Organisation des ministères et missions DGFiP/DGDDI/DGCCRF/INSEE/Trésor','QCM MEF + cartes erreurs']],['14:00–17:00','Comptabilité',['TVA collectée/déductible, immobilisations, TVA à décaisser/crédit','Analyse financière — passage 2, partie 2/2','12 calculs/écritures TVA','D071–D077 + F11']]]},
{date:'2026-09-16',label:'Mercredi 16 septembre',priority:'Comparer D1 et D2 sur un seul indicateur principal : lecture, plan ou rédaction.',blocks:[['06:00–11:00','NDS',['06:00–10:00 : DEVOIR 2 complet','10:00–11:00 : auto-audit, dépôt et comparaison des temps D1/D2']],['12:00–13:00','QCM Agent',['Actualité économique, sociale, internationale : fiches factuelles','QCM actualité + mix numérique/MEF']],['14:00–17:00','Comptabilité',['Exigibilité, régularisation, cas mélangés TVA + achats/ventes','Comptabilité générale — passage 3 complet','10 cas TVA chronométrés','D078–D084 + F12']]]},
{date:'2026-09-17',label:'Jeudi 17 septembre',priority:'Le jeudi sert à résorber les erreurs, pas à créer un nouveau retard.',blocks:[['09:00–11:00','QCM Agent',['Reprise des 20 erreurs les plus fréquentes depuis le 1er septembre','QCM mélangé toutes matières']],['14:00–16:30','Comptabilité',['Consolidation personnel + TVA','Comptabilité de gestion — passage 3 complet','Cas transversal 45 min + correction','D085–D090 + F13']]]},
{date:'2026-09-18',label:'Vendredi 18 septembre',priority:'Jalon : D2 rendu + simulation n°2 + TVA suffisamment solide pour les cas suivants.',blocks:[['09:00–11:30','QCM Agent',['Rappel actif rapide','Simulation Agent complète 1 h 30','Score + erreurs prioritaires']],['14:00–15:00','Comptabilité',['Rappel actif + 10 questions TVA','Reprise des 3 erreurs les plus fréquentes','D091–D096 + F14']]]}
]},
{id:'s4',title:'Semaine 4 — 21 au 25 septembre',goal:'Transformer le plan NDS en raisonnement et passer le QCM Agent en mode automatisation.',days:[
{date:'2026-09-21',label:'Lundi 21 septembre',priority:'Le plan NDS doit répondre à la commande, pas simplement classer les documents.',blocks:[['06:00–11:00','NDS',['Cours : plan dynamique, équilibre, titres explicites','Vidéo 4/10 : construction du plan + correction vidéo n°2','Produire 3 plans sur un même dossier','Transformer des titres faibles en titres démonstratifs','Comparer à une correction puis refaire le plan sans regarder']],['12:00–13:30','QCM Agent',['Cartes faibles maths/logique','Séries rapides, calcul mental, logique chronométrée']],['14:00–17:00','Comptabilité',['Opérations financières et avec l’étranger','Analyse financière — passage 3, partie 1/2','8 écritures financières/devises','D097–D102 + F15']]]},
{date:'2026-09-22',label:'Mardi 22 septembre',priority:'Concision : supprimer sans appauvrir.',blocks:[['06:00–11:00','NDS',['Plan sur nouveau sujet : 45 min','Introduction 15 min + réécriture de précision','Transitions/annonces : 8 phrases fonctionnelles','Avis/proposition 1 h 15','Réduire 20 phrases de 25 % + checklist']],['12:00–13:30','QCM Agent',['Cartes faibles histoire-géo/EMC','QCM culture générale officielle + actualité']],['14:00–17:00','Comptabilité',['Opérations hors exploitation/exceptionnelles + écarts de change','Analyse financière — passage 3, partie 2/2','10 écritures ciblées','D103–D108 + F16']]]},
{date:'2026-09-23',label:'Mercredi 23 septembre',priority:'Le devoir n°3 est la dernière grosse copie avant la semaine du concours Agent.',blocks:[['06:00–11:00','NDS',['06:00–10:00 : DEVOIR 3 complet','10:00–11:00 : auto-audit + dépôt ; 1 défaut de fond + 1 défaut de forme']],['12:00–13:00','QCM Agent',['Cartes faibles numérique/MEF','QCM numérique/MEF + questions mélangées']],['14:00–17:00','Comptabilité',['Trésorerie : banque, caisse, effets, agios, intérêts, règlements','Comptabilité générale — passage 4 complet','12 écritures de trésorerie','D109–D114 + F17']]]},
{date:'2026-09-24',label:'Jeudi 24 septembre',priority:'Simulation : travailler la précision sous chrono, pas chercher un record de vitesse.',blocks:[['09:00–11:00','QCM Agent',['Restitution sans support des grandes rubriques','Simulation Agent complète n°3']],['14:00–16:30','Comptabilité',['Rapprochement bancaire + stocks/variations','Comptabilité de gestion — passage 4 complet','1 rapprochement complet + 8 exercices stocks','D115–D120 + F18']]]},
{date:'2026-09-25',label:'Vendredi 25 septembre',priority:'Le programme Agent ne doit plus comporter de zone inconnue, seulement des fragilités identifiées.',blocks:[['09:00–11:30','QCM Agent',['Correction stratégique','Simulation Agent complète n°4','Classement final des erreurs à reprendre lundi 28']],['14:00–15:00','Comptabilité',['Synthèse activité de l’entreprise','20 min rappel + 30 min exercice mélangé + 10 min erreurs','D121–D126 + F19']]]}
]},
{id:'s5',title:'Dernière ligne droite — 28 au 30 septembre',goal:'Préserver le concours Agent, puis reprendre immédiatement la trajectoire Inspecteur.',days:[
{date:'2026-09-28',label:'Lundi 28 septembre',priority:'Arriver frais. La veille n’est pas une journée de rattrapage.',blocks:[['09:00–10:15','QCM Agent',['Uniquement fiches d’erreurs et faits à forte probabilité d’oubli','25–30 QCM faciles/moyens puis stop']],['10:30–11:45','Comptabilité',['Aucune nouveauté lourde','45 min définitions/formules + 30 min écritures flash','D127–D132 + F20']],['Après 11:45','Repos / concours',['Aucune NDS','Pas de simulation supplémentaire','Préparer matériel, trajet, sommeil et logistique']]]},
{date:'2026-09-29',label:'Mardi 29 septembre — CONCOURS AGENT',priority:'Une fois l’épreuve terminée, ne pas refaire le concours toute la soirée.',blocks:[['Avant l’épreuve','Repos / concours',['Aucun nouveau contenu','Échauffement mental très léger uniquement si utile']],['Épreuve','QCM Agent',['QCM officiel 1 h 30','Lecture précise, gestion du temps, éviter la précipitation']],['Après','Repos / concours',['Aucune comptabilité ni NDS','Fin de journée libre']]]},
{date:'2026-09-30',label:'Mercredi 30 septembre — BASCULE INSPECTEUR',priority:'Anglais, espagnol et droit pénal Douanes démarrent le 1er octobre, pas le 30.',blocks:[['06:00–11:00','NDS',['06:00–06:15 : relire la checklist personnelle','06:15–10:15 : DEVOIR 4 complet en conditions concours','10:15–11:00 : auto-audit + dépôt']],['12:00–13:30','QCM Inspecteur',['30 min diagnostic + Constitution, hiérarchie des normes, Conseil constitutionnel','60 min QCM diagnostic EAEF/UE/numérique/logique','Créer le score de départ Inspecteur']],['14:00–17:00','Comptabilité',['Investissements : actifs/passifs, typologie des immobilisations','Analyse financière — passage 4 complet','8 exercices charge vs immobilisation','D133–D138 + F21']]]}
]}
];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const allDays=weeks.flatMap(w=>w.days.map(d=>({...d,week:w.id,weekTitle:w.title,weekGoal:w.goal})));
const today=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();
const key=(d,bi,ti)=>`${d.date}|${bi}|${ti}`;
const flatTasks=d=>d.blocks.flatMap((b,bi)=>b[2].map((t,ti)=>({k:key(d,bi,ti),text:t})));
const statsForDays=ds=>{const tasks=ds.flatMap(flatTasks),done=tasks.filter(t=>state[t.k]).length;return{done,total:tasks.length,p:tasks.length?Math.round(done/tasks.length*100):0}};
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
const currentWeek=weeks.find(w=>w.days.some(d=>d.date===today))||weeks.find(w=>w.days.some(d=>d.date>today))||weeks[weeks.length-1];
function selectedWeeks(){if(view==='all')return weeks;if(view==='week')return[currentWeek];const d=allDays.find(x=>x.date===today);if(d)return[{id:d.week,title:d.label,goal:d.priority,days:[d]}];return[{id:'rest',title:'Aujourd’hui',goal:'Aucune révision lourde programmée.',days:[]}];}
function taskHtml(d,b,bi,t,ti){const k=key(d,bi,ti),done=!!state[k];return `<label class="task ${done?'done':''}"><input type="checkbox" data-k="${esc(k)}" ${done?'checked':''}><span>${esc(t)}</span></label>`}
function dayHtml(d){const s=statsForDays([d]),cls=d.date===today?'today':d.date<today?'past':'';return `<section class="card day-card ${cls}"><div class="day-head"><div><h3>${esc(d.label)}</h3><div class="date-sub">${esc(d.date)}</div></div><div class="day-score">${s.done}/${s.total} · ${s.p}%</div></div><div class="day-progress"><i style="width:${s.p}%"></i></div>${d.blocks.map((b,bi)=>`<div class="block"><div class="block-head"><span class="time-pill">${esc(b[0])}</span><span class="subject-pill">${esc(b[1])}</span></div><div class="task-list">${b[2].map((t,ti)=>taskHtml(d,b,bi,t,ti)).join('')}</div></div>`).join('')}<div class="priority"><b>Priorité :</b> ${esc(d.priority)}</div></section>`}
function render(){const month=statsForDays(allDays),week=statsForDays(currentWeek.days),day=statsForDays(allDays.filter(d=>d.date===today));const sel=selectedWeeks();APP.innerHTML=`<section class="program-hero"><div class="card hero"><h1>Ton programme de septembre</h1><p class="muted">Le concours Agent reste prioritaire jusqu’au 29 septembre. Le 30 septembre marque la bascule vers l’Inspecteur.</p><div class="program-stats"><div class="mini-stat"><b>${day.p}%</b><span>Aujourd’hui</span></div><div class="mini-stat"><b>${week.p}%</b><span>Semaine</span></div><div class="mini-stat"><b>${month.p}%</b><span>Mois</span></div></div></div><div class="card program-ring"><div class="ring" style="--p:${month.p}"><strong>${month.p}%</strong><small>${month.done}/${month.total} tâches</small></div></div></section><div class="view-tabs"><button class="chip ${view==='today'?'on':''}" data-view="today">Aujourd’hui</button><button class="chip ${view==='week'?'on':''}" data-view="week">Cette semaine</button><button class="chip ${view==='all'?'on':''}" data-view="all">Tout septembre</button></div><section class="card"><h2 style="margin-top:0">Objectifs du mois</h2><div class="month-goals"><div class="goal-card"><b>Note de synthèse</b><span>D1, D2, D3 et D4 rendus · 4/10 devoirs prépa terminés.</span></div><div class="goal-card"><b>Comptabilité</b><span>D001 à D138 implantées · F01 à F21 vues · passages 1 à 4.</span></div><div class="goal-card"><b>QCM Agent</b><span>Programme officiel revu · 4 simulations complètes + mini-simulation · concours du 29/09.</span></div><div class="goal-card"><b>QCM Inspecteur</b><span>Diagnostic initial le 30/09 · premières institutions françaises · banque d’erreurs créée.</span></div></div></section>${sel.map(w=>`<section><div class="week-head"><div><h2>${esc(w.title)}</h2><p class="muted">${esc(w.goal)}</p></div>${w.days.length?(()=>{const s=statsForDays(w.days);return`<div class="week-progress">${s.done}/${s.total}<div class="bar"><i style="width:${s.p}%"></i></div></div>`})():''}</div>${w.days.length?w.days.map(dayHtml).join(''):`<div class="card empty-day"><div class="rest-icon">☁</div><b>Pas de bloc prévu aujourd’hui</b><p class="muted">Le week-end reste sans dette de révision. Micro-rappel facultatif seulement.</p></div>`}</section>`).join('')}<section class="card safety"><h2 style="margin-top:0">Règles de sécurité du planning</h2><p>Ne pas sacrifier le sommeil pour finir le planning. Les devoirs et simulations sont des tests sans support, puis chaque erreur doit donner une action précise. Le week-end ne sert pas à absorber tous les retards.</p><button class="btn alt reset-program" id="resetProgram">Réinitialiser les coches</button><div class="source-note">Plan global de révision — Septembre 2026.</div></section>`;
APP.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;localStorage.setItem('programme-view',view);render()});
APP.querySelectorAll('input[data-k]').forEach(i=>i.onchange=()=>{state[i.dataset.k]=i.checked;if(!i.checked)delete state[i.dataset.k];save();render()});
const r=document.getElementById('resetProgram');if(r)r.onclick=()=>{if(confirm('Effacer tout le suivi du programme de septembre ?')){state={};save();render()}};
}
render();
})();