const CACHE='qcm-agent-douanes-v42';
const ASSETS=[
  './','./index.html','./v2.html','./cours.html','./programme.html','./informatique.html','./style-v2.css','./qcm-v4.css','./course-access.css','./programme.css','./informatique.css','./informatique-course.css','./helper.js','./math-course-bank.js','./math-contest-bank.js','./engine-logic.js','./knowledge-engine.js','./chapter-map.js','./qcm-engine-v8.js','./source-hygiene-v27.js','./source-hygiene-v28.js','./source-hygiene-v28b.js','./source-hygiene-v28c.js','./source-hygiene-v28d.js','./source-hygiene-v28e.js','./source-hygiene-v28f.js','./source-hygiene-v28g.js','./source-hygiene-v28h.js','./source-hygiene-v28i.js','./source-hygiene-v28j.js','./qcm-quality-guard.js','./pedagogy-v11.js','./formulation-v13.js','./strict-qcm-v25.js','./structured-qcm-v26.js','./qcm-rescue-v29.js','./qcm-rescue-v30.js','./history-curated-bank.txt','./geography-curated-bank.txt','./emc-curated-bank.txt','./actualite-200-bank.js','./organisation-250-bank.js','./culture-generale-250-bank.js','./culture-numerique-320-bank.js','./app-v7.js','./course-access.js','./course-index.js','./course-viewer.js','./programme.js','./informatique-bank.js','./informatique-bank-patch.js','./informatique-entry.js','./informatique-course.js','./informatique-course-view.js','./informatique.js','./install-app.js','./cours-maths.html','./manifest.webmanifest','./icon-192.svg','./icon-512.svg',
  './course-histoire.dat','./course-geographie.dat','./course-emc.dat','./clean-actualite.dat','./clean-organisation.dat','./clean-mathematiques.dat','./clean-logique.dat','./clean-culture-generale.dat',
  './bank-01.txt','./bank-02.txt','./bank-03.txt','./bank-04.txt','./bank-05.txt','./bank-06.txt','./bank-07.txt','./bank-08.txt','./bank-09.txt','./bank-10.txt','./bank-11.txt','./bank-12.txt',
  './history-timelines.css',
  './assets/geography/ordre-population-continents.svg','./assets/geography/oceans-et-mers.svg','./assets/geography/ordre-superficie-oceans.svg','./assets/geography/ordre-profondeurs-altitudes.svg','./assets/geography/passages-maritimes.svg','./assets/geography/grands-massifs.svg','./assets/geography/ordre-longueur-chaines.svg','./assets/geography/ordre-altitude-sommets.svg','./assets/geography/ordre-superficie-deserts.svg','./assets/geography/organisations-internationales-chronologie.svg','./assets/geography/reliefs-france.svg','./assets/geography/fleuves-france.svg','./assets/geography/mers-france.svg','./assets/geography/regions-capitales-france.svg','./assets/geography/outre-mer-statuts-carte.svg',
  './assets/history/timelines/01-fondements-civilisation.svg','./assets/history/timelines/02-france-origines-revolution.svg','./assets/history/timelines/03-revolution-empire.svg','./assets/history/timelines/04-xixe-siecle.svg','./assets/history/timelines/05-guerres-totalitarismes.svg','./assets/history/timelines/06-france-contemporaine.svg','./assets/history/timelines/07-presidents-hommes-etat.svg','./assets/history/timelines/08-revolutions-independances-monde.svg','./assets/history/timelines/09-culture-arts-litterature.svg','./assets/history/timelines/10-reperes-chronologiques.svg'
];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url),isCore=event.request.mode==='navigate'||/\.(?:js|css|html|webmanifest)$/.test(url.pathname);
  if(isCore){event.respondWith(fetch(event.request).then(async r=>{if(r&&r.ok&&url.origin===self.location.origin){const c=await caches.open(CACHE);c.put(event.request,r.clone())}return r}).catch(async()=>await caches.match(event.request,{ignoreSearch:true})||await caches.match('./v2.html')));return}
  event.respondWith(caches.match(event.request,{ignoreSearch:true}).then(cached=>cached||fetch(event.request).then(async r=>{if(r&&r.ok&&url.origin===self.location.origin){const c=await caches.open(CACHE);c.put(event.request,r.clone())}return r})));
});
